OpenVicProject/OpenVic-Simulation

src/openvic2/GameManager.cpp, src/openvic2/GameManager.hpp
Utilises GameManager's setup method to grab the init time for use as session ID for savegames, as well as setting up potential features in the future such as session time tracking for multiplayer.
=> Implement Session Start (SS-54)

src/openvic/GameManager.cpp, src/openvic/GameManager.hpp, src/openvic/Types.hpp, src/openvic/economy/Good.cpp, src/openvic/map/Building.cpp, src/openvic/map/Building.hpp, src/openvic/map/Map.cpp, src/openvic/map/Map.hpp, src/openvic/map/Province.cpp, src/openvic/map/Province.hpp, src/openvic/pop/Culture.cpp, src/openvic/pop/Culture.hpp, src/openvic/pop/Pop.cpp, src/openvic/pop/Pop.hpp, src/openvic/pop/Religion.cpp, src/openvic/pop/Religion.hpp
Data structures and managers for:
- Pop, PopType
- Religion, ReligionGroup
- Culture, Culture Group, GraphicalCultureType
Provinces have an internal Pop list, currently filled with hardcoded test Pops. Provinces keep track of their total population, and the map keeps track of its total population and the highest individual province population (which will be used in the Population Density mapmode).
Requirements implemented:
- POP-18, POP-19, POP-20, POP-21, POP-26
- MAP-65
=> Pops and other bits

src/openvic/map/Map.cpp
Changed `index < get_province_count()` to `index > get_province_count()` in check for invalid index in `set_selected_province`.
=> fixed silly mistake

src/openvic-simulation/GameManager.cpp, src/openvic-simulation/GameManager.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/economy/ProductionType.hpp
Should work as is, compiled and tested.
NOTE: the `poptype` field implements a "magic" identifier called `artisan`, as opposed to the actual pop type `artisans`. 
We speculate that refers to the `is_artisan` flag present in some pops.
In that case the `pop_type` field of `EmployedPop` is set to nullptr, and its boolean flag `artisan` will be set to `true`.
=> Implemented ProductionTypes

src/openvic-simulation/Modifier.cpp, src/openvic-simulation/Modifier.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/types/Vector.cpp, src/openvic-simulation/types/Vector.hpp
Only warnings left for me are the `#pragma once` things (which joe should already have fixed in his branch). When we merge Testing, we'll finally have a warn-free compilation. The built binary seems to work fine. 
Note: this applies to linux with `gcc`, haven't tested it on other systems/compilers.
=> Fixing compile-time warnings

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/Dataloader.hpp
Expose `Dataloader::parse_defines` 
Expose `Dataloader::parse_csv`
This is necessary in the case that a node refers to file like in countries.txt, any other solution would be less isolated and more complex.
=> Expose parse methods

.clang-format, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/Dataloader.hpp, src/openvic-simulation/dataloader/Dataloader_Windows.hpp, src/openvic-simulation/utility/ConstexprIntToStr.hpp
Searches for Victoria 2 according to the supplied path
If supplied path is empty, presumes Steam install according to platform environment variables
If invalid supplied path, falls back to empty path behavior
Supports Steam install on Windows, Mac, Linux, and FreeBSD
Supports Windows registry
Update .clang-format categories to include lexy-vdf
Add Utility/ConstexprIntToStr.hpp
=> Add static `Dataloader::search_for_game_path(fs::path)`

src/headless/main.cpp, src/openvic-simulation/Modifier.cpp, src/openvic-simulation/Modifier.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/Dataloader.hpp, src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/economy/Building.cpp, src/openvic-simulation/economy/Building.hpp, src/openvic-simulation/economy/Good.hpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/economy/ProductionType.hpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/map/TerrainType.cpp, src/openvic-simulation/map/TerrainType.hpp, src/openvic-simulation/military/Unit.cpp, src/openvic-simulation/military/Unit.hpp, src/openvic-simulation/politics/Government.cpp, src/openvic-simulation/politics/Government.hpp, src/openvic-simulation/pop/Culture.cpp, src/openvic-simulation/pop/Culture.hpp, src/openvic-simulation/types/IdentifierRegistry.cpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/types/fixed_point/FixedPoint.hpp, src/openvic-simulation/utility/Logger.cpp, src/openvic-simulation/utility/Logger.hpp
- Re-did headless mode Command Line Interface, giving more control over dataloader root paths and testing.
- Added `ModifierEffect::format_t` enum. Current values are `RAW_DECIMAL` (e.g. `attack`), `PERCENTAGE_DECIMAL` (e.g. `movement_cost`), and `INT` (e.g. `max_fort`).
- Re-did ModifierValue loading to provide functions supporting various combinations of modifier value callback, modifier effect whitelist, default key-value callback, and `expect_dictionary_keys`-style key_map and/or list of (key, expected_count, callback) triplets.
- Fixed `std::string_view` referring to destroyed `std::string` in `filename_equals`.
- Re-factored `expect_dictionary_keys` and related functions to use the same variadic induction function `add_key_map_entries` (modifier loading also uses this).
- Changed …
=> TGC compatibility fixes  + other cleanup

src/openvic-simulation/dataloader/Dataloader.cpp
Optimize allocations for `filename_equals`
=> Add constraint to `filename_equals`

src/openvic-simulation/history/Bookmark.cpp, src/openvic-simulation/history/Bookmark.hpp
In order to support the same feature set as Victoria 2, each newly created bookmark needs to be registered uniquely regardless of input. This would be a lot better with an index-based registry
=> Make Bookmarks indexed by indices

src/openvic-simulation/Modifier.cpp, src/openvic-simulation/Modifier.hpp, src/openvic-simulation/country/Country.cpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/economy/Building.cpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/map/TerrainType.cpp, src/openvic-simulation/military/LeaderTrait.cpp, src/openvic-simulation/military/LeaderTrait.hpp, src/openvic-simulation/military/Unit.cpp, src/openvic-simulation/politics/Government.cpp, src/openvic-simulation/pop/Culture.cpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp
Factored out the inner parts of `expect_fixed_point` and `expect_date` to `expect_fixed_point_str` and `expect_date_str`, which return `std::string_view` callbacks, to allow for string sources other than `expect_identifier`. The original functions still behave the same, but under the hood are just `expect_identifier(expect_*_str(...))`. I did this for fixed points and dates as those are data types which I know can appear in strings (i.e. quoted) in Vic2 defines, but other things like bool and int parsing could be refactored similarly.
`UniqueKeyRegistry::expect_item_identifier` already returned a `std::string_view` callback, so it has been renamed to `expect_item_str`, with the new `expect_item_identifier` behaving like the originally named functions above …
=> Cleanup + expect refactoring

src/openvic-simulation/Modifier.cpp
Used `naval` instead of `navy`, fixed.
Added TODO for technology group modifiers, should ideally be dynamic.
=> Fix Incorrect Modifier Effect

src/openvic-simulation/history/ProvinceHistory.cpp, src/openvic-simulation/history/ProvinceHistory.hpp
Fix a few variations of keys, add slave state status for split states, use `std::bitset` over individual update booleans.
=> Improve Province Histories

src/openvic-simulation/GameManager.hpp, src/openvic-simulation/country/Country.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/economy/EconomyManager.hpp, src/openvic-simulation/economy/Good.hpp, src/openvic-simulation/economy/ProductionType.hpp, src/openvic-simulation/history/DiplomaticHistory.hpp, src/openvic-simulation/history/HistoryManager.hpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/military/MilitaryManager.hpp, src/openvic-simulation/military/Unit.hpp, src/openvic-simulation/misc/Modifier.hpp, src/openvic-simulation/politics/Government.hpp, src/openvic-simulation/politics/Ideology.hpp, src/openvic-simulation/politics/Issue.hpp, src/openvic-simulation/politics/PoliticsManager.hpp, src/openvic-simulation/politics/Rebel.cpp, src/openvic-simulation/politics/Rebel.hpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/utility/Getters.hpp
This one should be pretty simple.
The complex values `will_rise`, `spawn_change`, `movement_evaluation`, `siege_won_trigger`, `siege_won_effect`, `demands_enforced_trigger` and `demands_enforced_effect` have been left unimplemented as requested.
I also did some macro work while I was at it, 'cause why not.
=> Dataloading rebels

src/openvic-simulation/GameManager.cpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/map/State.cpp, src/openvic-simulation/map/State.hpp
First pass, need some eyes on it. Overall philosophy is that the big `regions` vector should be kept up to date by functions that modify it with validation for states that need to be split or merged, but that might be better to eventually work into the `State` class itself.
Adds `State` struct.
Adds state member to Provinces
Adds logic for generating states, called on bookmark load.
=> States First Pass

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/history/CountryHistory.cpp, src/openvic-simulation/history/CountryHistory.hpp, src/openvic-simulation/research/Invention.hpp, src/openvic-simulation/research/Technology.hpp
Added:
- `Technology` loading
- `TechnologySchool` loading
- `Invention` loading
- Foreign investment loading
- A bunch of other keys that were missing, it only *seemed* to work because we had `success_callback` as default
=> Dataloading Country History - Part 2 

src/openvic-simulation/GameManager.cpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/economy/BuildingType.cpp, src/openvic-simulation/economy/BuildingType.hpp, src/openvic-simulation/history/ProvinceHistory.cpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/types/Vector.hpp
- Basic adjacency generation refactor + additional adjacency loading
- Land-land, water-water and land-water adjacencies are differentiated, and land provinces in a coastal adjacency have their coastal flag set.
- The first BuildingType with the port flag set is recorded, and errors are printed for any further ones with the port flag set.
- Coastal provinces with a building position for the recorded port BuildingType have their port flag set.
- Added mapmodes for displaying adjacencies of the currently selected province and for displaying provinces with their port flag set.
=> Additional adjacency loading

src/openvic-simulation/utility/BMP.cpp, src/openvic-simulation/utility/BMP.hpp
Change `BMP::palette` to  `std::vector<palette_colour_t>`
Change `BMP::PALETTE_COLOUR_SIZE` to use `sizeof(palette_colour_t)`
Silence warning for `header.num_colours - 1 >> header.bits_per_pixel == 0`
=> Add `BMP::palette_colour_t` as uint32_t

src/openvic-simulation/GameManager.cpp, src/openvic-simulation/GameManager.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/economy/BuildingInstance.cpp, src/openvic-simulation/economy/BuildingType.cpp, src/openvic-simulation/economy/BuildingType.hpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/types/Date.cpp, src/openvic-simulation/types/Date.hpp
- Record province building types in a list, with their index in that list being used to identify them in the UI-SIM interface (eg when expanding buildings).
- Selected province is now stored as a province pointer rather than a province index.
- Date to double conversion removed, float is still used for expansion progress (as it has no impact on the simulation) but in general floating point use should be discouraged.
=> Province building scaffolding

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/politics/PoliticsManager.hpp, src/openvic-simulation/politics/Rule.cpp, src/openvic-simulation/politics/Rule.hpp
`Rule` and `RuleSet` operate similarly to `ModifierEffect` and `ModifierValue`, with `bool` values instead of `fixed_point_t`. `RuleSet`s can be combined using the overloaded `|` and `|=` operators, with conflicting rules defaulting to `true`/`yes`. `RuleSet`s can be loaded from `ast::NodeCPtr`s using `expect_rule_set`.
(NOT FULLY TESTED - will be used and tested in zaaarf's issue/reform loading PR)
=> Added political/policy rules

src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/map/Region.cpp, src/openvic-simulation/map/Region.hpp, src/openvic-simulation/map/State.cpp, src/openvic-simulation/map/State.hpp
- `ProvinceSet` now stores `Province const*`s. It no longer has a constructor that accepts a vector of provinces (as that might contain duplicates), instead it has an `add_provinces` function that calls the `add_province` function with every element of a vector and returns false if any of those calls fail. It also has a `remove_province` function.
- `Map` has a `remove_province_const` that allows a non-const `Map` to be used to remove a `Province const*`'s const qualifier (equivalent to looking up the province by its ID, but faster).
- `Region` no longer takes a vector of provinces as a constructor argument, instead they are added using `ProvinceSet`'s `add_provinces`. Since it doesn't get its provinces in its constructor, it needs to get its colour directly, which is handled by …
=> Made ProvinceSet use Province const* and updated Region loading

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/map/Region.cpp, src/openvic-simulation/map/Region.hpp, src/openvic-simulation/map/TerrainType.hpp
The `Climate` and `Continent` structs would've been perfectly identical, so I created one `ProvinceSetModifier` struct with `Climate`and `Continent` as aliases. They are both a list of provinces associated with some modifiers, so they should each be a `ProvinceSet`, and conversely the provinces should have references to their `Climate` and `Continent`. Both references - the one stored in the `Climate`/`Continent` and the one(s) stored in `Province` - should be stored as `const` pointers.
~~To ensure that the reference to `Climate` and `Continent` each `Province` holds is immutable, I had to make that annoying for loop at the end. It's only ran once, so the double loop isn't too much a performance concern.~~
~~It's maybe worth looking into making a variant of `ProvinceSet` holding …
=> Dataloading climate and continents

.clang-format
Clang 18 format options should be commented out for now because Clang 18 is not out
=> Disable AllowShortCompoundRequirementOnASingleLine

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/economy/BuildingType.cpp, src/openvic-simulation/economy/BuildingType.hpp, src/openvic-simulation/economy/Good.cpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/misc/Modifier.cpp, src/openvic-simulation/politics/Issue.cpp, src/openvic-simulation/politics/Rule.cpp, src/openvic-simulation/politics/Rule.hpp
- Rules now have a group, if that group is mutually exclusive then `trim_and_resolve_conflicts` removes disabled rules in that group as well as any enabled rules beyond the one with the lowest index (from order of definiton).
- Added `build_*` rules for every building type type (i.e. the `type` identifier of `BuildingType`s), with a special case for `railroad` which has type `infrastructure` but rule `build_railway`.
- Fixed reform tech cost warnings.
- Moved issue&reform and delayed poptype loading until after rules setup, which has itself been moved to after building type loading.
- Added some missing modifiers (for TGC compatibility), changed artisan/factory input modifiers not to be `positive_good` and removed RGO input modifiers.
=> Mutually exclusive rule groups + modded building rules

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/dataloader/Vic2PathSearch.cpp, src/openvic-simulation/scripts/ConditionalWeight.cpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/types/OrderedContainers.hpp, src/openvic-simulation/utility/StringUtils.hpp
- Added case insensitive string hash and equal structs.
- Added `case_insensitive_ordered_map` and `case_insensitive_ordered_set`.
- Added `CaseInsensitiveIdentifierRegistry` and `CaseInsensitiveIdentifierInstanceRegistry`.
- Updated `string_map_t` and `UniqueKeyRegistry` related templates to accept `Hash` and `KeyEqual` parameters.
- Fixed event file `Parser`s not being cached.
- Added temporary `days` and `years` keys to `ConditionalWeight` so that mod parsing succeeds, these will be replaced as part of an upcoming `expect_dictionary_keys` rework PR.
- Fixed `get_item_identifiers` returning loads of empty identifiers (it was allocating space for all the identifiers but then adding them on top of that, so the allocated space just contained empty `std::string_view`s).
=> Added case insensitive ordered set and map and IdentifierRegistry

src/openvic-simulation/military/Unit.cpp, src/openvic-simulation/military/Unit.hpp
Victoria 2 has 3 options to restrict cultures for units.
1. Only primary culture
2. All accepted cultures
3. All cultures
The restriction is determined by a combination of `primary_culture = [yes/no]` & `accepted_culture = [yes/no]`.
The default value for both is no/false. `accepted_culture` overrules `primary_culture`.
This leaves 3 code paths:
1. primary_culture && !accepted_culture => Only primary culture
2. accepted_culture => All accepted cultures
3. !primary_culture && !accepted_culture => All cultures
=> Support culture restrictions for units

src/openvic-simulation/GameManager.cpp, src/openvic-simulation/history/CountryHistory.cpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/politics/Rebel.cpp
- Allow coastal and water adjacencies to be made impassable (they just get deleted rather than having an impassable adjacency saved, as we don't need them registered for blue borders like we do with impassable land adjacencies).
- Allow country history government flag overrides to appear in multiple blocks.
- Make rebel independence and defection non-mandatory and change defaults to `NONE`.
=> More impassable adjacencies + WVPM mod fixes

src/openvic-simulation/GameManager.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/map/Crime.cpp, src/openvic-simulation/military/Wargoal.cpp, src/openvic-simulation/misc/Decision.cpp, src/openvic-simulation/misc/Event.cpp, src/openvic-simulation/misc/Event.hpp, src/openvic-simulation/misc/Modifier.cpp, src/openvic-simulation/politics/Ideology.cpp, src/openvic-simulation/politics/Issue.cpp, src/openvic-simulation/politics/NationalFocus.cpp, src/openvic-simulation/politics/Rebel.cpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/research/Invention.cpp, src/openvic-simulation/research/Technology.cpp, src/openvic-simulation/scripts/Condition.cpp, src/openvic-simulation/scripts/Condition.hpp, src/openvic-simulation/scripts/ConditionScript.cpp, src/openvic-simulation/scripts/ConditionScript.hpp, src/openvic-simulation/scripts/ConditionalWeight.cpp, src/openvic-simulation/scripts/ConditionalWeight.hpp, src/openvic-simulation/scripts/ScriptManager.hpp
This one's a mess. 
We have `Condition`s, representing any "valid node" in condition blocks (which includes both condition scopes and proper conditions). This behaviour may be changed in the future. `Condition` stores information about that "type of node" - what value it can take, whether it's an identifier of something and of what if it is, and so on.
Then you have `ConditionNode`s, which store a `Condition` and its value, (which may also be a list of `ConditionNode`s, forming a tree-like structure).
Following up on the skeleton implemented in #112, blocks requiring conditions of some kind will store a `ConditionScript`, which will contain an empty `ConditionNode`, a `NodeCPtr` storing a reference to the tree node to parse and, if needed, metadata (such as the initial scope, `factor` …
=> Condition definition checking/loading

src/openvic-simulation/country/Country.cpp, src/openvic-simulation/country/Country.hpp, src/openvic-simulation/dataloader/Dataloader.hpp, src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/diplomacy/DiplomaticAction.cpp, src/openvic-simulation/history/CountryHistory.cpp, src/openvic-simulation/history/ProvinceHistory.cpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/military/Wargoal.cpp, src/openvic-simulation/misc/Event.cpp, src/openvic-simulation/misc/Modifier.cpp, src/openvic-simulation/politics/NationalFocus.cpp, src/openvic-simulation/politics/NationalFocus.hpp, src/openvic-simulation/politics/Rebel.cpp, src/openvic-simulation/politics/Rule.cpp, src/openvic-simulation/pop/Culture.cpp, src/openvic-simulation/pop/Culture.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/scripts/Condition.cpp, src/openvic-simulation/types/HasIdentifier.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/types/OrderedContainers.hpp
- Added `map_callback`, which includes a check for duplicates, and used it in dataloading code.
- Added more `expect_item_dictionary` variants, including `and_length` and `reserve_length` variants.
=> Added map_callback and expect_item_dictionary_reserve_length

src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/economy/ProductionType.hpp
Artisanal production ignores owners and employees.
RGO & factory production requires both.
`poptype = artisan` is never valid. It's simply ignored for artisanal production.
Several properties were renamed to reflect their meaning instead of their name in production_types.txt.
=> Improved validation of production types and renamed properties to be descriptive

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/interface/LoadBase.hpp, src/openvic-simulation/misc/Modifier.cpp, src/openvic-simulation/misc/Modifier.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp
`UniqueKeyRegistry` now has 4 concept-validated template paramters:
- `ValueInfo` - contains the type being registered + a unique identifier string getter function. Currently implemented for `HasIdentifier` (used where the string and other attributes are known beforehand) and `Named` (used where the string and other attributes are loaded post-construction via a chain of key-callback adding virtual functions).
- `_ItemInfo` - contains the type the `Value`s are actually stored in, so either `Value` itself of `std::unique_ptr<Value>`. as well as item->value [const] reference conversion functions.
- `_StorageInfo` - contains the container the items are put in, either `std::vector` or `std::deque`, as well as an index type used in the string-index lookup map together with functions to get the …
=> Reworked `UniqueKeyRegistry` template params

src/headless/main.cpp, src/openvic-simulation/GameManager.cpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/diplomacy/DiplomaticAction.hpp, src/openvic-simulation/economy/BuildingType.cpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/economy/ProductionType.hpp, src/openvic-simulation/history/ProvinceHistory.cpp, src/openvic-simulation/military/Deployment.cpp, src/openvic-simulation/military/Deployment.hpp, src/openvic-simulation/military/Unit.cpp, src/openvic-simulation/misc/Event.cpp, src/openvic-simulation/misc/Modifier.cpp, src/openvic-simulation/politics/Rebel.cpp, src/openvic-simulation/pop/Culture.cpp, src/openvic-simulation/pop/Culture.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/research/Invention.cpp, src/openvic-simulation/types/Colour.hpp, src/openvic-simulation/types/FunctionRef.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/utility/Logger.hpp, src/openvic-simulation/utility/StringUtils.hpp
- Removed the need to include the `mod` folder when specifying mods to be loaded in headless mode.
- Added message count tracking to `Logger`, and a summary output at the end of headless mode (useful for checking if a change increased the number of warnings or errors).
- Implemented missing parsing for some basic defines variables (and added comments explaining why others weren't being loaded):
- Loaded `primary` and `union` countries for `Culture`s and `CultureGroup`s, which required moving culture loading to be after country loading. Also loaded `radicalism` for `Culture`.
- Loaded `picture` string for OOB `Leader`s.
- Loaded `PopType` incomes from national budget, research and leadership points and optimum ratio for whichever points a `PopType` generates, tax efficiency and equivalent …
=> Parse missing variables, Logger counting, misc cleanup

src/openvic-simulation/dataloader/Vic2PathSearch.cpp, src/openvic-simulation/utility/StringUtils.hpp
Fixes OpenVicProject/OpenVic#195
Enables actually searching for game path
Reports info or warning depending on why it fails
Remove StringUtils.hpp include in Vic2PathSearch.cpp
Add <cstdint> to StringUtils.hpp
=> Harmonize empty result behavior for `_search_for_game_path`

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/interface/LoadBase.hpp, src/openvic-simulation/military/Deployment.cpp, src/openvic-simulation/military/Deployment.hpp, src/openvic-simulation/military/Unit.cpp, src/openvic-simulation/military/Unit.hpp, src/openvic-simulation/misc/Modifier.cpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp
To be merged after #137 
- Replaced Unit parameter macros with argument structs, a shared unit one and one each for land and naval specific parameters.
- Renamed `type_t` to `branch_t` and added `unit_type_t` macro.
- Added unit terrain modifiers, which created a circular dependency that I fixed by delaying `PopType` rebel unit composition parsing so that I could move `_load_map_dir` before `_load_units`.
- Added `movement` modifier effect, confirmed to work in unit terrain modifiers.
- Added `IdentifierPointerRegistry`, which provides the external interface of an `IdentifierRegistry` without storing its own data -used for providing access to a `Unit` base class registry even though the actual objects are stored in separate land and naval unit registries. This way we can …
=> Reworked Units and added IdentifierPointerRegistry

src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/interface/GFX.cpp, src/openvic-simulation/interface/GFX.hpp, src/openvic-simulation/interface/GUI.cpp, src/openvic-simulation/interface/GUI.hpp, src/openvic-simulation/interface/LoadBase.hpp, src/openvic-simulation/map/TerrainType.cpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/types/OrderedContainers.hpp, src/openvic-simulation/utility/Utility.hpp
- Added `StringMapCase`s, combining case [in]sensitive string hash and equal types, together with an intermediate struct that remembers the `StringMapCase` to help with template deduction for `string_map_t`s and `string_set_t`s.
- Replaced `IdentifierRegistry`'s `RegistryIdentifierMapInfo` with `StringMapCase` (the same concept restrictions, but now applied directly to the internal string map instead of being decomposed into hash and equal types).
- Made `expect_dictionary_keys` functions take a `StringMapCase` template argument,  so that they can also be case insensitive (used in GUI and GFX loading). This involved moving lots of functions from `NodeTools.cpp` to `NodeTools.hpp`, the only changes to them are adding the template parameters and replacing `*_callback_t` with `*Callback …
=> Added StringMapCase and case insensitive expect_dictionary_keys

src/openvic-simulation/GameManager.cpp, src/openvic-simulation/country/Country.cpp, src/openvic-simulation/country/Country.hpp, src/openvic-simulation/interface/GUI.cpp, src/openvic-simulation/interface/GUI.hpp, src/openvic-simulation/map/Map.cpp, src/openvic-simulation/map/Map.hpp, src/openvic-simulation/map/Province.cpp, src/openvic-simulation/map/Province.hpp, src/openvic-simulation/politics/Issue.cpp, src/openvic-simulation/politics/Issue.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/types/fixed_point/FixedPoint.hpp, src/openvic-simulation/types/fixed_point/FixedPointMap.hpp
- Add `border_size` to `GUI::Text`.
- Add `fixed_point_map_t` operators and helper functions.
- Generate `Issue` and `Reform` colours and clean up their loading code.
- Add `CountryParty` colours (from their `Ideology`).
- Add `Pop` attributes, some of which have placeholder/test values:
- location
- total change
- ideologies, issues, votes (currently with equal distributions generated for testing)
- unemployment
- cash, income, expenses, savings
- life, everyday and luxury needs fulfilment
=> GUI and Pop attribute work for Population Menu

src/openvic-simulation/country/Country.cpp, src/openvic-simulation/country/Country.hpp, src/openvic-simulation/map/Region.cpp, src/openvic-simulation/map/Region.hpp, src/openvic-simulation/politics/Government.cpp, src/openvic-simulation/politics/Government.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp
Small additions needed for main repo menu stuff:
- country index - to map countries to their flags in the flag sheet.
- `ProvinceSet::calculate_total_population` - to display the population of `Region`s in the population menu (later this will be changed to `State` populations, using the same function as states will be `ProvinceSet`s).
Minor tweaks:
- flag types are now stored in a `string_set_t` which handles the uniqueness checks for us.
- `Region::get_meta` is now created by the `PROPERTY` macro.
- whitespace/newline fixes in `IdentifierRegistry.hpp` and `Country.cpp`.
=> Menu reqs: country index, flag type set, province set total population

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/country/CountryDefinition.cpp, src/openvic-simulation/country/CountryDefinition.hpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/economy/GoodDefinition.cpp, src/openvic-simulation/economy/GoodDefinition.hpp, src/openvic-simulation/history/CountryHistory.cpp, src/openvic-simulation/history/CountryHistory.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/Mapmode.cpp, src/openvic-simulation/map/Mapmode.hpp, src/openvic-simulation/map/ProvinceDefinition.cpp, src/openvic-simulation/map/ProvinceDefinition.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/politics/NationalFocus.cpp, src/openvic-simulation/politics/NationalFocus.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/types/HasIdentifier.hpp, src/openvic-simulation/types/IndexedMap.hpp
There are probably more places we can switch to using IndexedMap, e.g. for a Pop's Reform/Issue support distribution (although their current setup using separate registries/indexing means they can't be stored in a single IndexedMap), but I'll leave those for future PRs.
=> Add IndexedMap and use in low key count, high value density cases

src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/military/UnitType.cpp
Saves between 500-550ms on my local Linux debug tests.
=> Use rvalue references for NodeTools

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/economy/EconomyManager.hpp, src/openvic-simulation/economy/ProductionType.cpp, src/openvic-simulation/economy/ProductionType.hpp, src/openvic-simulation/military/UnitType.cpp, src/openvic-simulation/military/UnitType.hpp, src/openvic-simulation/military/Wargoal.cpp, src/openvic-simulation/military/Wargoal.hpp
=> Optimize some string interning cases 

src/headless/main.cpp, src/openvic-simulation/DefinitionManager.hpp, src/openvic-simulation/GameManager.cpp, src/openvic-simulation/GameManager.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/Dataloader.hpp, src/openvic-simulation/misc/SongChance.cpp, src/openvic-simulation/misc/SongChance.hpp, src/openvic-simulation/misc/SoundEffect.cpp, src/openvic-simulation/misc/SoundEffect.hpp
This is the sim portion of the music and Sound defines pr, needs review (code style?).
Main changes are:
- Addition of SongChance and SoundEffect loaders
- Dataloader now has separated root setting, and define loading functions so that the title_theme soundtrack can be loaded before the defines. Other files like GameSingleton and main.cpp changed to match.
=> Music and Sound Effect define loading

src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp
I had to change this as fixed_point_t can't handle int64. Also pop size shouldn't exceed int32.
We need fixed_point_t for calculations.
=> Reduce pop size to int32

src/openvic-simulation/economy/BuildingType.cpp, src/openvic-simulation/economy/BuildingType.hpp, src/openvic-simulation/economy/EconomyManager.hpp, src/openvic-simulation/economy/GoodDefinition.cpp, src/openvic-simulation/military/UnitType.cpp, src/openvic-simulation/misc/Modifier.cpp, src/openvic-simulation/misc/Modifier.hpp, src/openvic-simulation/politics/Rebel.cpp, src/openvic-simulation/politics/Rule.cpp, src/openvic-simulation/politics/Rule.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/research/Technology.cpp, src/openvic-simulation/utility/StringUtils.hpp
There are a few modifiers which don't have localisation keys, e.g. `min_build_***` and some `***_RGO_SIZE` modifiers.
=> ModifierEffect and Rule localisation keys

.gitignore, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/map/MapDefinition.cpp, src/openvic-simulation/map/MapDefinition.hpp
Loads the rivers bitmap into structure that the sim can eventually use for movement and combat checks. No graphics in this PR, probably going to shelve working on river graphics and focus on sim-side as I get more availability to contribute again.
Tested, loads 905 rivers successfully in vanilla.
=> Simulation Side Rivers

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/history/CountryHistory.cpp, src/openvic-simulation/history/CountryHistory.hpp, src/openvic-simulation/history/ProvinceHistory.cpp
As requested by #191.
This was pretty much a glorified copy-paste operation. If you think it would be better, I'm open to try and remake the add/remove core/culture lambda as a single function with templates, but I'm not sure of where I could put it. Also, it may be overkill. Depends how many more times will we have to do this.
By the way, fixed a small mistake in add/remove_core's logging. 
Tested it and it appears to work.
=> Added support for remove_culture custom instruction

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/map/ProvinceInstance.cpp
A province contributes its modifiers to its controller, not the owner.
A province is affected by the modifiers of the owner, not the controller.
=> Provinces contribute modifiers to controller, not owner

src/openvic-simulation/map/MapInstance.cpp
Victoria 2 uses the last pop history <= startdate.
If none is available, it picks the first pop history > startdate.
=> Always apply pop history

src/headless/main.cpp, src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/InstanceManager.hpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/dataloader/Vic2PathSearch.cpp, src/openvic-simulation/economy/GoodDefinition.cpp, src/openvic-simulation/economy/GoodDefinition.hpp, src/openvic-simulation/economy/GoodInstance.cpp, src/openvic-simulation/economy/GoodInstance.hpp, src/openvic-simulation/economy/production/ArtisanalProducer.hpp, src/openvic-simulation/economy/production/Employee.cpp, src/openvic-simulation/economy/production/Employee.hpp, src/openvic-simulation/economy/production/FactoryProducer.hpp, src/openvic-simulation/economy/production/ProductionType.cpp, src/openvic-simulation/economy/production/ProductionType.hpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp, src/openvic-simulation/history/ProvinceHistory.cpp, src/openvic-simulation/history/ProvinceHistory.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/Mapmode.cpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/map/State.cpp, src/openvic-simulation/map/State.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp
1. trade_goods from history are converted to actual RGO instances.
2. pops are converted to equivalents if applicable (farmer <> labourer).
3. RGO size is calculated.
4. Province rgo can be changed (this will convert pops and update the rgo).
5. When initialising a new game RGO hires workers, produces good and gives income to owners and employees.
=> Prepare for rgo

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/map/State.cpp, src/openvic-simulation/map/State.hpp
Cache pops by type so RGOs and factories can quickly iterate over owner pops when paying.
=> Cache pops by type per state and province

src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp
I added the stores directly to the pop type. I thought of creating an object for them but worried it would hurt performance. I also considered making them a single array but worried that might hurt readability. For the clear_income_per_source() function, I wasn't sure how to get it to trigger every tick, and I'm not sure creating new fixed_point objects would be the most efficient approach. One idea I had was to zero out the sources by subtracting them from themselves, but I was worried that would cause problems since the economy is parallelized.
=> Added stores for pop Income solves #225

src/openvic-simulation/modifier/ModifierEffectCache.cpp
This was caught when @BrickPi noticed errors running the program on ARM64 Mac
=> Initialise `ModifierEffectCache::supply_limit_global_base` to `nullptr`

src/openvic-simulation/dataloader/Vic2PathSearch.cpp
Another mac fix-up, for whatever reason, after failing to find a steam install and asking me to point to my Vic2 install (in this case a network drive shared with windows), the current function ignores the entry and fails, whereas this branch succeeds and works as expected. Not sure why, as the folder is called "Victoria 2", but removing that statement additionally makes it less confusing for people to load OpenVic if they've renamed their Victoria 2 folder - instead relying on the presence of v2game.exe alone, which is still a pretty safe bet.
=> Fix Backup Path Search Ignoring User-Selected Directory

src/openvic-simulation/utility/BMP.cpp
This fixes mods like TTA which use [BMPs with 0 as their image data size entry](https://github.com/The-Third-Age/TTA-Victoria-2/blob/main/map/provinces.bmp).
=> Relax BMP data size constraint (allow 0 as unset)

src/openvic-simulation/country/CountryDefinition.cpp, src/openvic-simulation/country/CountryDefinition.hpp, src/openvic-simulation/politics/Ideology.hpp
This fixes a crash when country parties have a missing or invalid ideology entry, allowing their ideology variable to be null in that case (following Vic2's approach of showing such parties as having "No Ideology" rather than crashing).
=> Allow CountryParty ideology to be nullptr

src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/economy/production/ProductionType.cpp, src/openvic-simulation/economy/production/ProductionType.hpp, src/openvic-simulation/interface/UI.cpp, src/openvic-simulation/map/Crime.cpp, src/openvic-simulation/map/MapDefinition.cpp, src/openvic-simulation/map/TerrainType.cpp, src/openvic-simulation/map/TerrainType.hpp, src/openvic-simulation/military/Deployment.cpp, src/openvic-simulation/military/UnitType.cpp, src/openvic-simulation/modifier/Modifier.cpp, src/openvic-simulation/modifier/Modifier.hpp, src/openvic-simulation/modifier/ModifierEffectCache.cpp, src/openvic-simulation/modifier/ModifierEffectCache.hpp, src/openvic-simulation/modifier/ModifierManager.cpp, src/openvic-simulation/pop/Culture.cpp, src/openvic-simulation/pop/PopType.cpp, src/openvic-simulation/research/Technology.cpp, src/openvic-simulation/research/Technology.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp, src/openvic-simulation/types/fixed_point/FixedPoint.hpp, src/openvic-simulation/utility/Getters.hpp
Also:
- improve `fixed_point_t` print function (now `decimal_places = -1` let's it use however many it needs, matching the behaviour of Godot's float-to-string functions)
- make `PROPERTY` getters `[[nodiscard]]`
- make `CountryInstance`'s `capital` a non-const pointer with a non-const getter function
- add a `PROPERTY` getter for `ResourceGatheringOperation`'s `location_ptr`
- fix format and colour rules for `war_exhaustion` and `max_war_exhaustion` `ModifierEffect`s
=> Add TerrainType movement_cost, IdentifierRegistry back(), allow no trigger Crimes

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/InstanceManager.hpp, src/openvic-simulation/economy/GoodInstance.cpp, src/openvic-simulation/economy/GoodInstance.hpp, src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/production/ArtisanalProducer.hpp, src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.cpp, src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.hpp, src/openvic-simulation/economy/trading/BuyResult.hpp, src/openvic-simulation/economy/trading/BuyUpToOrder.cpp, src/openvic-simulation/economy/trading/BuyUpToOrder.hpp, src/openvic-simulation/economy/trading/MarketInstance.cpp, src/openvic-simulation/economy/trading/MarketInstance.hpp, src/openvic-simulation/economy/trading/SellResult.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/misc/GameRulesManager.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/types/fixed_point/FixedPoint.hpp, src/openvic-simulation/utility/CompilerFeatureTesting.hpp
Artisans will buy inputs from the market using BuyUpToOrder.
They will buy up to `input amount - amount in stockpile`.
As each input can bottleneck production, artisans aim to maximise `min(inputs satisfied)`.
Based on this they allocate money to buy the inputs.
Each GoodInstance has a maximum next price, this is the price artisans take into account when allocating funds.
=> Add Artisanal production + buying from market

src/openvic-simulation/dataloader/Dataloader.cpp
Windows and macOS can actually support per-path case sensitive filesystem behavior. Doesn't really cost much of anything since its very likely that if this check fails on the case sensitive case, it was already gonna cause the dataloading behavior to completely fail anyway.
=> Fix Windows/macOS insensitive filesystem presumption

.github/workflows/builds.yml, deps/SCsub
Fixes linkage errors building with `dev_build=yes` for the OpenVic repo
=> Fix glib not linking libtbb

.github/workflows/builds.yml, .gitignore, .gitmodules, SConstruct, src/openvic-simulation/pathfinding/AStarPathing.cpp, src/openvic-simulation/pathfinding/AStarPathing.hpp, src/openvic-simulation/pathfinding/FringePathing.cpp, src/openvic-simulation/pathfinding/FringePathing.hpp, src/openvic-simulation/pathfinding/PathingBase.hpp, src/openvic-simulation/pathfinding/PointMap.cpp, src/openvic-simulation/pathfinding/PointMap.hpp, src/openvic-simulation/types/VectorN.inc, src/openvic-simulation/utility/Utility.hpp, tests/SCsub, tests/deps/SCsub, tests/src/Helper.hpp, tests/src/pathfinding/AStarPathing.cpp, tests/src/pathfinding/FringePathing.cpp, tests/src/pathfinding/Pathing.hpp, tests/src/pathfinding/PointMap.cpp
Add Fringe pathfinding
Add PointMap
Add unit testing with snitch-org/snitch@2a594333016b9cfc1f90b116184cb0bdbf98a480
Add `distance_squared` function to vectors
Add `dot` function to vectors
Add `hash_murmur3` function to Utility.hpp
=> Add AStar pathfinding (and unit testing)

src/openvic-simulation/economy/GoodInstance.cpp, src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/trading/BuyResult.hpp, src/openvic-simulation/economy/trading/MarketInstance.cpp, src/openvic-simulation/economy/trading/SellResult.hpp
This simplifies the code and fixes the `artisan expense 0` warnings.
=> Return money spent, instead of money left

SConstruct, src/openvic-simulation/console/ConsoleInstance.cpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/NodeTools.cpp, src/openvic-simulation/history/HistoryMap.hpp, src/openvic-simulation/map/MapDefinition.cpp, src/openvic-simulation/types/Colour.cpp, src/openvic-simulation/types/Colour.hpp, src/openvic-simulation/types/Date.cpp, src/openvic-simulation/types/Date.hpp, src/openvic-simulation/types/Vector.cpp, src/openvic-simulation/types/Vector.hpp, src/openvic-simulation/types/VectorN.inc, src/openvic-simulation/types/fixed_point/FixedPoint.hpp, src/openvic-simulation/utility/Utility.hpp, tests/SCsub, tests/src/Helper.hpp, tests/src/pathfinding/PointMap.cpp, tests/src/types/Approx.hpp, tests/src/types/Colour.cpp, tests/src/types/Date.cpp, tests/src/types/FixedPoint.cpp, tests/src/types/Numeric.hpp, tests/src/types/Timespan.cpp, tests/src/types/Vector.hpp, tests/src/types/Vector2.cpp, tests/src/types/Vector3.cpp, tests/src/types/Vector4.cpp
Add Fixed Point unit tests
Add Vector unit tests
Add Colour unit tests
Add Date unit tests
Add Timespan unit tests
Add Approx to assist floating point comparisons
Separate unit test build and run options
Add double Vector (for testing)
Add Vector <=>, >, >=, <, <= operators
Add Vector cross-type operators
Add `fixed_point_t::_0_25()`
Add Fixed Point float comparison operators
Make fixed_point_t(int64) constructor explicit
Fix fixed_point_t Vector abs function
Add rgb and rgba integer parsing to Colour
Add Colour string parse methods
Add invert operator to Colour
Add full_invert to Colour (includes alpha)
Add _rgba Colour user-defined literal
Add Timespan prefix and postfix -- operators
Add Timespan to_chars method
Add Date prefix and postfix -- operators
Add Date to_chars method
Improve …
=> Add more unit tests

src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/map/Region.cpp, src/openvic-simulation/map/Region.hpp, src/openvic-simulation/military/LeaderTrait.cpp, src/openvic-simulation/military/LeaderTrait.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp
Also changes `reserve_more` to add to capacity rather than size so it can be used multiple times in a row
=> Store vectors of personality and background leader traits to choose from when generating leaders

src/openvic-simulation/country/CountryInstance.hpp
- initialise country inventions count to 0
- make country military `has_*` functions return bools
=> CountryInstance fixes

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/economy/trading/GoodMarket.cpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/types/fixed_point/FixedPoint.hpp, tests/src/types/FixedPoint.cpp
`fixed_point_t * fixed_point_t / fixed_point_t`
First does `parse_raw(lhs.value * rhs.value >> PRECISION)` which becomes 0 for small values.
Any division (by even by a small value) is then useless.
`mul_div` avoids the shifts and preserves accuracy.
See also https://discord.com/channels/1063392556160909312/1105422859641290803/1340640042523168811
=> Improve calculation accuracy by avoiding shifting via mul_div

src/openvic-simulation/country/CountryDefinition.cpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/politics/Issue.cpp, src/openvic-simulation/politics/Issue.hpp, src/openvic-simulation/pop/Pop.cpp
Also adds definition index variables to `IssueGroup` and `ReformGroup`.
These features are intended to help with Politics Menu setup
=> Store vectors of Issues/Reforms under each IssueGroup/ReformGroup

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/economy/GoodInstance.cpp, src/openvic-simulation/economy/GoodInstance.hpp, src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/production/ArtisanalProducer.hpp, src/openvic-simulation/economy/trading/GoodMarket.cpp, src/openvic-simulation/economy/trading/GoodMarket.hpp, src/openvic-simulation/economy/trading/MarketInstance.cpp, src/openvic-simulation/economy/trading/MarketInstance.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/pop/PopValuesFromProvince.cpp, src/openvic-simulation/pop/PopValuesFromProvince.hpp, src/openvic-simulation/types/Vector.hpp
- Assign properties instead of unused local variables.
- Multiply by `1 + modifier` instead of only the modifier.
- Correct local variable name
- Skip logic when max_quantity == 0
- Add space before \ (in macros)
- Reset country data, then do province ticks and then country ticks (otherwise country tick resets the data generated in province tick)
- Skip pop needs that aren't available yet.
- Renamed tick to country_tick so it's easier to find its uses.
- Added GoodDefinition to GoodMarket for easier debugging
- Extracted allocate_needs to a method instead of a macro for easier debugging.
- Update cash_left_to_spend even when a pop couldn't afford max price.
- In ArtisanalProducer::add_to_stockpile use .find() & .at() instead of indexing to allow parallel execution.
=> Fix pop need modifiers

src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/politics/Issue.cpp, src/openvic-simulation/politics/Issue.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/PopType.cpp, src/openvic-simulation/pop/PopType.hpp
- Needed for budget menu where strata UI elements are identified by index (0 = poor, 1 = middle, 2 = rich). Previous system indexed stratas based on their order of appearance in loaded pop type files, for vanilla: rich, middle, poor.
- This also adds a `default_strata`, following the base game's behaviour of defaulting to middle strata for invalid defines file strata values.
- This adds a vector of pop types to each strata so we can easily iterate over their pop types.
- This adds index variables to Strata and PopType, so they can be reliably identified by ints rather than strings.
=> Fix strata order to: poor, middle, rich

src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/production/ArtisanalProducer.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/pop/PopValuesFromProvince.cpp, src/openvic-simulation/pop/PopValuesFromProvince.hpp
Pops use several `GoodDefinition::good_definition_map_t` in their tick method. These maps can be cleared and reused by the next pop. `PopValuesFromProvince` similarly can be reused for multiple provinces as all data is overwritten in the `update_pop_values_from_province` method.
So to reuse resources when possible, `PopValuesFromProvince` is expanded to include several reusable maps.
The MapInstance now stores the instances of `PopValuesFromProvince` and creates threads explicitly to process provinces in parallel. This is done to limit the number of threads to the number of `PopValuesFromProvince`s.
`std::thread::hardware_concurrency()` is used to determine the amount of worker threads. Those threads are created in the map tick to process the provinces. The parent thread also processes …
=> Performance: reuse maps & PopValuesFromProvince

src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/economy/trading/GoodMarket.cpp, src/openvic-simulation/economy/trading/MarketInstance.cpp, src/openvic-simulation/economy/trading/MarketInstance.hpp, src/openvic-simulation/pop/Pop.cpp
Round up income to epsilon when you have sold a good.
Round up expenses to epsilon when you have bought a good.
Round up money_to_spend when allocating to buy a good (so `money_to_spend >= max_next_price * max_quantity_to_buy`).
Round down quanity bought
=> Round up income and expenses to handle inaccuracies

src/headless/main.cpp, src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/InstanceManager.hpp, src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/misc/SimulationClock.cpp, src/openvic-simulation/misc/SimulationClock.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp
#337 rounded up expenses.
The artisanal optimal quantity was calculated as if we have endless precision and no rounding.
(Also optimal quantity wasn't used. Demand was used instead.)
The optimal quantity needs to take the minimum cost of epsilon into account. This is a flat cost and not proportional to the quantity bought.
Other changes:
- added force_tick_and_update to simulate several days in headless
- rounded up income for RGO workers (#337 should've included this...)
- minor spacing corrections in pop files
=> Fix artisan overspending

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/utility/ThreadPool.cpp, src/openvic-simulation/utility/ThreadPool.hpp
- Use max_worker_threads instead of threads.size() to fill threads as size start 0 (even after resizing).
- Renamed `initialise` to `initialise_threadpool` so you can search for it easily.
- Use different locks for the thread condition and the completed condition to avoid deadlocking.
- Pass `work_type` reference as reference instead of passing it by value as that will never change.
=> Fix bugs in threadpool

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/misc/GameRulesManager.hpp
In Victoria 2, the owner collects taxes and gold income even when provinces are occupied.
It makes more sense that the controller gets that. Alternatively occupied territories could be considered in disarray and neither the owner nor the controller are able to collect taxes.
All of this is now supported via game rules.
=> Add game rule for economic country

src/openvic-simulation/dataloader/NodeTools.cpp
Add early callback skip to `NodeTools::expect_colour`
Add early callback skip to NodeTools expect vec2 functions
Add early callback skip to `NodeTools::expect_fvec3`
Add early callback skip to `NodeTools::expect_fvec4`
Add early return for `NodeTools::expect_list_and_length`
=> Add early callback skip to type-specific expect functions

src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/utility/StringUtils.hpp
Reworks the callback so the key map is passed along.
This allows us to log valid keys to aid modders instead of merely specifying their key is invalid.
=> Log valid keys in expect_dictionary_keys

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/map/State.hpp
The switch to passing `InstanceManager` to update functions is partly in preparation for condition scripts which will need `InstanceManager const&` to be executed
=> Add geographical province and country stats

src/openvic-simulation/map/ProvinceDefinition.cpp, src/openvic-simulation/types/Colour.hpp
Add fmt formatter support to basic_colour_t
Optimize `operator<<(std::ostream&, basic_colour_t const&)`
Remove stringstream in `ProvinceDefinition::to_string`
=> Add stack string methods to basic_colour_t

src/openvic-simulation/types/Colour.hpp, src/openvic-simulation/types/Date.cpp, src/openvic-simulation/types/Date.hpp, src/openvic-simulation/types/Vector.hpp, src/openvic-simulation/types/fixed_point/FixedPoint.cpp, src/openvic-simulation/types/fixed_point/FixedPoint.hpp, src/openvic-simulation/utility/StringUtils.hpp, src/openvic-simulation/utility/Utility.hpp, tests/src/types/Approx.hpp, tests/src/types/Colour.cpp, tests/src/types/Colour.hpp, tests/src/types/Date.cpp, tests/src/types/FixedPoint.cpp, tests/src/types/Numeric.hpp, tests/src/types/Timespan.cpp, tests/src/types/Vector.hpp, tests/src/types/Vector2.cpp, tests/src/types/Vector3.cpp, tests/src/types/Vector4.cpp
Add constexpr support for `basic_colour_t::to_chars`
Fix constexpr support for `basic_colour_t::parse_from_chars`
Add constexpr support for `Date::to_chars`
Add constexpr support to `Date::from_string`
Add constexpr support to vector abs method
Fix constexpr support `StringUtils::from_chars`
Add constexpr support for `fixed_point_t::to_chars`
Fix constexpr support for `fixed_point_t::parse`
Fix constexpr support for fixed_point_t constants
Add Approx constexpr support
Add constexpr to_chars in StringUtils.hpp
Add constexpr abs in Utility.hpp
=> Add constexpr unit tests

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/country/SharedCountryValues.cpp, src/openvic-simulation/country/SharedCountryValues.hpp, src/openvic-simulation/dataloader/NodeTools.hpp, src/openvic-simulation/misc/GameRulesManager.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp, src/openvic-simulation/pop/PopNeedsMacro.hpp, src/openvic-simulation/pop/PopType.cpp, src/openvic-simulation/pop/PopType.hpp
Implements administration, education & military spending as well as pensions and unemployment subsidies.
=> Government salaries and social income

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/economy/BuildingType.cpp, src/openvic-simulation/economy/GoodDefinition.cpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/map/TerrainType.cpp, src/openvic-simulation/military/UnitType.cpp, src/openvic-simulation/modifier/ModifierEffect.cpp, src/openvic-simulation/modifier/ModifierEffect.hpp, src/openvic-simulation/modifier/ModifierEffectCache.cpp, src/openvic-simulation/modifier/ModifierEffectCache.hpp, src/openvic-simulation/modifier/ModifierManager.cpp, src/openvic-simulation/modifier/ModifierManager.hpp, src/openvic-simulation/politics/Rebel.cpp, src/openvic-simulation/pop/PopType.cpp, src/openvic-simulation/research/Technology.cpp
updated modofiers dp so that they match the way Vic 2 displays them
=> Update Modifiers dp 

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/production/ArtisanalProducer.hpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/economy/trading/BuyResult.hpp, src/openvic-simulation/economy/trading/BuyUpToOrder.hpp, src/openvic-simulation/economy/trading/GoodMarket.cpp, src/openvic-simulation/economy/trading/GoodMarket.hpp, src/openvic-simulation/economy/trading/MarketSellOrder.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/utility/ThreadPool.cpp, src/openvic-simulation/utility/ThreadPool.hpp
=> Domestic market & imports

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/map/State.cpp, src/openvic-simulation/map/State.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/Pop.hpp
Negative tariffs are handled with a 1 tick delay.
This allows the game to accurately project the cost and ensure the actual costs never exceed the projected costs (which might lead to bankruptcy otherwise).
In `Pop::after_buy` the pop keeps a running total of `yesterdays_import_value`.
This is cleared after calling `CountryInstance::request_salaries_and_welfare_and_import_subsidies` in `Pop::pop_tick`.
In the `update_gamestate` methods, `yesterdays_import_value` is propagated from province via state to country, just like total population.
In `CountryInstance::country_tick_before_map` the `projected_import_subsidies` are calculated and `actual_import_subsidies` is determined after handling budget cuts due to cash shortages.
`CountryInstance::request_salaries_and_welfare_and_import_subsidies …
=> Negative tariffs

src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/economy/trading/GoodMarket.cpp, src/openvic-simulation/economy/trading/GoodMarket.hpp, src/openvic-simulation/history/ProvinceHistory.cpp, src/openvic-simulation/map/MapDefinition.cpp, src/openvic-simulation/map/MapDefinition.hpp, src/openvic-simulation/map/ProvinceInstance.cpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/utility/BMP.cpp, src/openvic-simulation/utility/BMP.hpp
"Everywhere that you use std::vector<T> const& could you instead use std::span<T> as it reduces indirection and generalizes the use case instead of being dependent on the vector type being passed. It would allow any contiguous finite array of elements, dynamic or static, to be passed in and also doesn't depend on an allocator to describe the type."
https://github.com/OpenVicProject/OpenVic-Simulation/pull/291#issuecomment-2961121242
=> Move const reference vectors to span

src/openvic-simulation/InstanceManager.cpp, src/openvic-simulation/map/MapDefinition.cpp, src/openvic-simulation/map/Region.cpp, src/openvic-simulation/map/Region.hpp, src/openvic-simulation/map/State.cpp
Previously when a province was assigned to multiple regions in a mod, the game would simply crash.
Now it reports which province is assigned to which regions and asserts that all land provinces have a state.
=> Graceful handling of provinces with multiple regions

src/openvic-simulation/politics/Issue.cpp, src/openvic-simulation/scripts/Condition.cpp, src/openvic-simulation/scripts/Condition.hpp, src/openvic-simulation/scripts/ConditionScript.cpp, src/openvic-simulation/scripts/ConditionScript.hpp, src/openvic-simulation/scripts/EffectScript.cpp, src/openvic-simulation/scripts/EffectScript.hpp, src/openvic-simulation/scripts/Script.hpp
In vanilla, event 16000 (A House Divided) has multiple `immediate` effect nodes. They need to be combined.
Third Age uses multiple `allow` nodes for a political reform. Victoria 2 simply combines them via AND.
To support this, scripts now store a vector of nodes instead of a single one.
=> Support multiple script nodes by combining them

SConstruct
Reference for generated data is
```cpp
namespace OpenVic {
static constexpr std::string_view SIM_TAG;
static constexpr std::string_view SIM_RELEASE;
static constexpr std::string_view SIM_COMMIT_HASH;
static constexpr const uint64_t SIM_COMMIT_TIMESTAMP;
}
```
=> Streamline commit_info.gen generator in SConstruct

src/openvic-simulation/country/CountryDefinition.hpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/economy/GoodDefinition.hpp, src/openvic-simulation/economy/production/ArtisanalProducer.cpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/history/Bookmark.hpp, src/openvic-simulation/history/DiplomaticHistory.cpp, src/openvic-simulation/map/Mapmode.cpp, src/openvic-simulation/map/Mapmode.hpp, src/openvic-simulation/map/ProvinceDefinition.cpp, src/openvic-simulation/map/ProvinceDefinition.hpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/politics/Issue.hpp, src/openvic-simulation/politics/Rule.hpp, src/openvic-simulation/pop/PopType.cpp, src/openvic-simulation/pop/PopType.hpp, src/openvic-simulation/research/Technology.hpp, src/openvic-simulation/types/HasIdentifier.hpp
Before there was no way to use `==` with 2 references.
The developer had to decide whether to convert both to pointers or compare their indices (or their identifiers (if applicable)).
While comparing the pointers works and so far is the standard, support `==` directly using the indices is easier to use and still correct. Index + type is unique.
This does require tagging HasIndex with the type for context.
=> Support == for HasIndex using type tagging

src/openvic-simulation/utility/Logger.cpp, src/openvic-simulation/utility/Logger.hpp
Fixes `ld: warning: duplicate symbol 'thread-local initialization routine for OpenVic::Logger::log_scope_stack'` issue when building on macOS with Clang 17.
=> Fix log scope duplicated symbol error with clang

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp
The budget menu requires taxable income per strata for the projected tax income.
CountryInstance stores taxable income per pop type. A simple filtered sum should suffice.
=> Added get_strata_taxable_income to CountryInstance

src/openvic-simulation/country/CountryInstance.cpp
All government salaries & social spending uses a base value which is not scaled by pop size.
When scaling by pop size, we must divide by `Pop::size_denominator`.
=> Government salaries & social welfare / Pop::size_denominator

AUTHORS.md, SConstruct
- Depends on #477 
Add compile-time author info generator
Reference for generated data is
```cpp
namespace OpenVic {
static constexpr std::array<std::string_view> SIM_AUTHORS_SENIOR_DEVELOPERS;
static constexpr std::array<std::string_view> SIM_AUTHORS_DEVELOPERS;
static constexpr std::array<std::string_view> SIM_AUTHORS_CONTRIBUTORS;
static constexpr std::array<std::string_view> SIM_AUTHORS_CONSULTANTS;
}
```
Note: This is not an exhaustive list of correct information, especially for consultants, if any information should be corrected or changed I would recommend contacting me, I have left any non-usernames out aside from mine even if it is identified with the email or Github account to minimize overstepping the desired boundaries. If anyone would like their proper (full or partial) name …
=> Add AUTHORS.md

src/openvic-simulation/types/fixed_point/FixedPoint.hpp, tests/src/types/FixedPoint.cpp
fixed_point_t only supported truncating to int32_t and int64_t.
Rounding before truncating could be done via explicit `floor()` or `ceil()`.
This PR just adds `to_int64_t_rounded()` which rounds away from zero.
There is also a `to_int32_t_rounded()` which merely casts the int64 to int32.
=> Round fixed_point_t to int away from zero

src/openvic-simulation/types/BasicIterator.hpp, src/openvic-simulation/types/CowPtr.hpp, src/openvic-simulation/types/CowVector.hpp, src/openvic-simulation/types/Signal.hpp, src/openvic-simulation/utility/Deque.hpp, src/openvic-simulation/utility/Utility.hpp
In majority of cases, a copy-on-write type should be a vector, cow_vector reduces reference indirection from cow_ptr
Add basic_iterator: For common type-safe contigious iterator functionality
Replace `cow_ptr<std::vector>` in basic_signal with `cow_vector`
=> Add cow_vector

src/openvic-simulation/modifier/StaticModifierCache.hpp
#384 refactored static modifiers and causes runtime parsing issues.
```
[ERROR] NodeTools.hpp(282): Duplicate expected dictionary key: base_values
[WARNING] ModifierManager.cpp(781): This modifier does nothing: import_cost
[ERROR] NodeTools.hpp(130): Invalid dictionary key: second_power
[ERROR] NodeTools.cpp(345): Callback failed for assign node with key: second_power
[ERROR] NodeTools.hpp(324): Mandatory dictionary key not present: secondary_power
[ERROR] Dataloader.cpp(1087): Failed to load static modifiers!
```
=> Fix static modifier names

src/openvic-simulation/history/CountryHistory.cpp, src/openvic-simulation/history/HistoryMap.hpp, src/openvic-simulation/history/ProvinceHistory.cpp
```
Invalid dictionary key "civilised". Valid values are [capital, primary_culture, culture, remove_culture, religion, government, plurality, nationalvalue, civilized, prestige, ruling_party, 
last_election, upper_house, oob, schools, foreign_investment, literacy, non_state_culture_literacy, consciousness, nonstate_consciousness, is_releasable_vassal, decision, govt_flag, colonial_points, set_country_flag, 
clr_country_flag, set_global_flag, clr_global_flag]
```
Instead of `Invalid dictionary key "civilised".` only.
=> Improve invalid key message in history

.gitmodules
foonathan/memory has an incomplete .gitignore and marks generated files as dirty.
The generated files marked as dirty:
- include/foonathan/memory/config_impl.hpp
- include/foonathan/memory/detail/container_node_sizes_impl.hpp
- *.obj
This PR ignores all changes in that submodule.
=> Ignore foonathan/memory gen files

src/openvic-simulation/types/HasIdentifier.hpp, src/openvic-simulation/types/HasIndex.hpp, src/openvic-simulation/types/IndexedMap.hpp
IndexedMap searches for an item to get the index.
If the item inherits from HasIndex, it has a `get_index()` method which should be used instead.
This is faster than searching.
=> Use index from HasIndex in IndexedMap

src/openvic-simulation/country/CountryInstance.cpp
Expenses didn't impact the `cash_stockpile` of a country. The code was simply never implemented.
This PR subtracts expenses from cash_stockpile in `country_tick_before_map`.
An alternative implementation is to subtract it per pop in `request_salaries_and_welfare_and_import_subsidies`.
Since `cash_stockpile` is a `moveable_atomic_fixed_point_t` and that method would be executed per pop, that would result in significantly more overhead. The benefit from that approach would be subtracting the exact costs per pop.
The approach of this PR has the downside of letting the country pay for rounding errors.
Pop salaries, welfare & import subsidies are truncated. The differences should be minimal and acceptable.
=> Subtract expenses from cash_stockpile in country_tick_before_map

src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/types/CowVector.hpp
Fixes two issues preventing builds on latest macOS with latest Xcode toolchain.
Blocker for my progress on #470.
=> Fix CowVector.hpp and Pop.cpp not compiling under apple clang 17

src/openvic-simulation/politics/Ideology.cpp, src/openvic-simulation/politics/Ideology.hpp
Inheriting from HasIndex allows indexing directly in IndexedMaps instead of searching, thus improving performance.
=> Add HasIndex to ideology

src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/defines/CountryDefines.hpp
The tooltip in budget menu needs to display the effect of admin spending on crime as well as administrator percentage and the desired percentage.
=> Properties for admin eff tooltip

src/openvic-simulation/console/ConsoleInstance.cpp, src/openvic-simulation/history/ProvinceHistory.cpp, src/openvic-simulation/map/MapDefinition.cpp, src/openvic-simulation/map/MapDefinition.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/Mapmode.cpp, src/openvic-simulation/map/ProvinceDefinition.cpp, src/openvic-simulation/map/ProvinceDefinition.hpp, src/openvic-simulation/misc/GameAction.cpp, src/openvic-simulation/pathfinding/AStarPathing.cpp, src/openvic-simulation/types/HasIndex.hpp, src/openvic-simulation/types/IdentifierRegistry.hpp
#496 uses the index from HasIndex to directly index arrays. This is great for performance but requires 0-based indexing.
Provinces use 1-based indexing for their 'external id' (data-loading, UI & console).
To remedy this, provinces now use 0-based indices for HasIndex and clearly marked 1-based indices for pathfinding, console, game actions and such.
=> Clearly distinguish between 0- & 1-based indexing

src/headless/main.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/map/State.hpp, src/openvic-simulation/military/UnitInstanceGroup.hpp, src/openvic-simulation/utility/Getters.hpp
Instead `get_##NAME()` returning a `vector<T> const&` it now returns a `forwardable_span<const T>`.
This ensures the collection is const, but if T is a pointer to a non-const type, the instance it points to is non-const.
This is required for #508 as it requires non-const instances to get data that may update a cache.
If desired, the forwardable_span return could be exposed as non-const with the `vector<T> const&` remaining as const variant.
That would result in different return types between const and non-const `get_##NAME()`.
=> Expose vector properties via span

src/openvic-simulation/console/ConsoleInstance.cpp, src/openvic-simulation/console/ConsoleInstance.hpp, src/openvic-simulation/map/MapDefinition.cpp, src/openvic-simulation/map/MapDefinition.hpp, src/openvic-simulation/map/MapInstance.cpp, src/openvic-simulation/map/MapInstance.hpp, src/openvic-simulation/map/Mapmode.cpp, src/openvic-simulation/map/ProvinceDefinition.cpp, src/openvic-simulation/map/ProvinceDefinition.hpp, src/openvic-simulation/map/ProvinceInstance.hpp, src/openvic-simulation/misc/GameAction.cpp, src/openvic-simulation/pathfinding/AStarPathing.cpp, src/openvic-simulation/types/IdentifierRegistry.hpp
#504 split 0-based and 1-based indices. Spartan and I agreed that indices should always be 0-based.
So we need a different name for 1-based values (used for provinces).
province_id was rejected as id is typically short for identifier and province identifiers (strings) also exist.
Spartan recommended province_number instead. This PR changes the names.
=> Refactor index_1_based to province_number

src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Operators that modify a fixed_point_t directly must return the reference to it, not a copy.
Operators:
- +=
- -=
- *=
- /=
- %=
=> Return fixed_point_t& for *= and such

src/headless/main.cpp, src/openvic-simulation/GameManager.cpp, src/openvic-simulation/GameManager.hpp, src/openvic-simulation/dataloader/Dataloader.cpp, src/openvic-simulation/dataloader/Dataloader.hpp, src/openvic-simulation/dataloader/ModManager.cpp, src/openvic-simulation/dataloader/ModManager.hpp, tests/benchmarks/src/dataloading/Dataloading.cpp
A couple of improvements to mod loading in preparation for main repo ModMenu work.
- Moves generic modloading logic from headless simulation to GameManager
- Loads all mod descriptors present on disk (so that we can present them to the user in an in-game mod menu)
- Loads selected mods + dependencies, with improved error handling and (simple) cycle prevention.
- Allows users to specify full name or shorthand mod name when loading mods on command line ("HPM" and "Historical Project Mod 0.4.6" are both valid, for instance)
=> Load all mod descriptors and check dependencies

src/openvic-simulation/country/CountryParty.hpp, src/openvic-simulation/map/State.hpp, src/openvic-simulation/military/UnitBranchedGetterMacro.hpp, src/openvic-simulation/modifier/ModifierEffectCache.hpp, src/openvic-simulation/politics/PoliticsInstanceManager.hpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/PopValuesFromProvince.cpp, src/openvic-simulation/types/Colour.cpp, src/openvic-simulation/types/IndexedFlatMapMacro.hpp, src/openvic-simulation/types/Vector.cpp, src/openvic-simulation/types/fixed_point/FixedPointMap.hpp, src/openvic-simulation/utility/ErrorMacros.hpp
Replace `// depends on ...` with actual imports inside macro headers.
Use `// IWYU pragma: keep` to tell the IDE to keep imports.
Added comments explaining why `// IWYU pragma: keep` is used.
Shortened imports of .hpp file in related .cpp file to `Vector.hpp` instead of `openvic-simulation/types/Vector.hpp`
Split up `auto view = owner->get_country_definition()->get_parties()` to check for null and explicitly use CountryDefintion, so the IDE will keep the header import.
=> Use IWYU pragma: keep

src/openvic-simulation/types/OrderedContainersMath.hpp
_"For iterators, operator*() and operator->() return a reference and a pointer to const std::pair<Key, T> instead of std::pair<const Key, T> making the value T not modifiable. To modify the value you have to call the value() method of the iterator to get a mutable reference."_
Source https://github.com/Tessil/ordered-map?tab=readme-ov-file#differences-compared-to-stdunordered_map
=> Use mutable it.value() for ordered_map += and such

src/headless/main.cpp, src/openvic-simulation/country/CountryInstance.cpp, src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/country/SharedCountryValues.cpp, src/openvic-simulation/country/SharedCountryValues.hpp, src/openvic-simulation/economy/production/Employee.cpp, src/openvic-simulation/economy/production/Employee.hpp, src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp, src/openvic-simulation/map/State.cpp, src/openvic-simulation/map/State.hpp, src/openvic-simulation/misc/GameAction.cpp, src/openvic-simulation/pop/Pop.cpp, src/openvic-simulation/pop/PopType.hpp, src/openvic-simulation/pop/PopValuesFromProvince.cpp, src/openvic-simulation/pop/PopsAggregate.cpp, src/openvic-simulation/pop/PopsAggregate.hpp, src/openvic-simulation/types/Signal.hpp, src/openvic-simulation/types/SliderValue.hpp, src/openvic-simulation/utility/MathConcepts.hpp, src/openvic-simulation/utility/reactive/DependencyTracker.hpp, src/openvic-simulation/utility/reactive/DerivedState.hpp, src/openvic-simulation/utility/reactive/MutableState.hpp
- Supersedes #508 
When it comes to reactivity in the UI I'd love to use a reactive pull based model.
Where the reactive part is event-driven marking data as dirty.
The pull part would be the UI updating all elements marked dirty.
This would be kinda like Svelte, but Svelte does it compile-time.
Sadly according to Gemini and my own research neither godot nor C++ have something like this.
We're stuck with signals and manually invalidating or directly updating UI elements.
Also we have to ensure that signals can't flood the UI with updates.
This is a error-prone approach.
I thought about it some more and came up with the following high-level idea:
Split state up into:
constant state
mutable state (properties with events)
derived state (tracks dependencies is marked dirty when they update. …
=> Automatic dependency tracking

src/openvic-simulation/country/CountryInstance.hpp, src/openvic-simulation/utility/reactive/MutableState.hpp
If you pass extra arguments to STATE_PROPERTY, they will be passed to the constructor via `MutableState<T> { __VA_ARGS__ };`.
=> Support initialisation in STATE_PROPERTY

src/openvic-simulation/utility/reactive/DerivedState.hpp, src/openvic-simulation/utility/reactive/MutableState.hpp
In `MutableState<T>` the signal is `signal<T>`, so the connection method pointer should be invocable with T.
Also in `T const& get(ConnectTemplateType&& connect)` the `connect` method is invoked with a `signal<T>&`, not a `signal<T>` technically.
=> Correct connection methods

src/openvic-simulation/country/CountryInstance.hpp
`fixed_point_t get_tariff_efficiency() const;` was replaced by `DerivedState<fixed_point_t> tariff_efficiency;` See #523 
`void update_country_definition_based_attributes();` is no longer relevant since country definition is const. See #526
=> Remove CountryInstance methods without implementation

src/openvic-simulation/utility/reactive/DependencyTracker.hpp, tests/src/utility/reactive/DerivedState.cpp
is_dirty_lock is meant to only protect is_dirty.
The changed() callback could request the up to date value, which would mark is_dirty false.
Unit test included.
=> Lock is_dirty_lock shorter

src/headless/main.cpp, src/openvic-simulation/utility/Logger.hpp
While we'll be moving to dropping mac support, libc++ has supported source_location for a while now anyway, so there's not reason to keep the conditional around any longer since every major library implementation now handles source_location properly anyway.
=> Make conditional std::source_location use unconditional
