OpenVicProject/OpenVic-Simulation

- src/openvic/Types.cpp
- src/openvic/Types.hpp
- src/openvic/economy/Good.cpp
- src/openvic/economy/Good.hpp
- src/openvic/map/Map.cpp
- src/openvic/map/Province.cpp
- src/openvic/map/Province.hpp
- src/openvic/pop/Culture.cpp
- src/openvic/pop/Culture.hpp
- src/openvic/pop/Pop.cpp
- src/openvic/pop/Pop.hpp
- src/openvic/pop/Religion.cpp
- src/openvic/pop/Religion.hpp
- Added combined `HasIdentifierAndColour` class
- Added distributions as `std::unordered_map<HasIdentifierAndColour const*, float>`
> Added distributions for pop type and culture

- src/openvic/pop/Pop.cpp
- src/openvic/pop/Pop.hpp
REQ POP-34, POP-35, POP-36, POP-37.
Changed pop_size_t type alias to int64_t (previously u_int32_t).
Added Pop properties
- num_migrated
- pop_daily_change
Added PopType properties
- num_promoted
- num_demoted
- num_migrated
Added PopType new constructor arguments.
Added PopType getters
- get_num_promoted()
- get_num_demoted()
- get_num_migrated()
- get_pop_daily_change()
> Added pop properties + changes to pop_size_t type

- src/headless/main.cpp
- src/openvic-simulation/GameManager.cpp
- src/openvic-simulation/Modifier.cpp
- src/openvic-simulation/Modifier.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/economy/Good.cpp
- src/openvic-simulation/map/Building.cpp
- src/openvic-simulation/map/Map.cpp
- src/openvic-simulation/map/Map.hpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
- src/openvic-simulation/map/Region.cpp
- src/openvic-simulation/map/Region.hpp
- src/openvic-simulation/pop/Culture.cpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
- src/openvic-simulation/pop/Religion.cpp
- src/openvic-simulation/types/Colour.hpp
- src/openvic-simulation/types/IdentifierRegistry.cpp
- src/openvic-simulation/types/IdentifierRegistry.hpp
- src/openvic-simulation/types/Vector.cpp
- src/openvic-simulation/types/Vector.hpp
- src/openvic-simulation/utility/Logger.hpp
- Region and meta region loading
- Localisation loading
- First go at Modifiers (ModifierEffect, ModifierValue, Modifier, ModifierInstance and ModifierManager)
> More dataloading

- src/openvic-simulation/map/Map.cpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
Implemented the adjacency stuff as requested
> Basic province adjacencies algorithm/logic

- src/openvic-simulation/GameManager.cpp
- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/economy/Good.cpp
- src/openvic-simulation/economy/Good.hpp
- src/openvic-simulation/units/Unit.cpp
- src/openvic-simulation/units/Unit.hpp
Should work, more or less. There's a couple TODOs, but I'm not sure we can implement them at this stage, so they'll probably have to stay there.
> Dataloading for military (Unit, LandUnity, NavalUnit)

- src/openvic-simulation/politics/Issue.cpp
- src/openvic-simulation/politics/Issue.hpp
It compiles and runs without errors, so I call myself satisfied, but do check the code please.
> Dataloading for Politics MK2 (semi-separation of Issues and Reforms)

- SConstruct
This fixes an issue of environment leakage which causes all sorts of problems.
Depends on OpenVicProject/OpenVic-Dataloader#19
> Fix environment issues

- src/openvic-simulation/GameManager.cpp
- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/Modifier.cpp
- src/openvic-simulation/Modifier.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/economy/Good.cpp
- src/openvic-simulation/economy/ProductionType.cpp
- src/openvic-simulation/map/Map.cpp
- src/openvic-simulation/map/Map.hpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
- src/openvic-simulation/map/TerrainType.cpp
- src/openvic-simulation/map/TerrainType.hpp
- src/openvic-simulation/types/Date.cpp
- src/openvic-simulation/types/IdentifierRegistry.hpp
- src/openvic-simulation/utility/BMP.cpp
- src/openvic-simulation/utility/BMP.hpp
- Moved terrain bmp loading to this repo
- `terrain.txt` loading + parsing
- Terrain type modifier calculation based on number of pixels of each type in the province
- Added simple terrain mapmode
> Terrain types

- src/openvic-simulation/GameManager.cpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/economy/ProductionType.hpp
- src/openvic-simulation/map/Building.cpp
- src/openvic-simulation/map/Building.hpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
- src/openvic-simulation/units/Unit.cpp
- src/openvic-simulation/units/Unit.hpp
Should be fine. Compiled and tested on both Windows (MSVC) and Linux (GCC), but do try it on your own.
> Dataloading buildings

- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
Loads positions.txt information, tests passing.
> Implement Province Positions Loading

- src/openvic-simulation/GameManager.cpp
- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/politics/Government.cpp
- src/openvic-simulation/politics/Government.hpp
Does what it says on the tin, feature-complete, tests passing.
FS-525, SIM-27
> Implement Government Type Loading

- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/history/Bookmark.cpp
- src/openvic-simulation/history/Bookmark.hpp
- src/openvic-simulation/history/HistoryManager.hpp
Testing passes, bookmark identifiers are just the string of the date, might be better to use the name however I was unsure with it being a localization value, only other alternative is storing it sequentially.
> Add Bookmark Loading

- src/openvic-simulation/Modifier.cpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/military/LeaderTrait.cpp
- src/openvic-simulation/military/LeaderTrait.hpp
- src/openvic-simulation/military/MilitaryManager.hpp
Loads leader traits, tests passing.
> Implement Trait Loading

- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/country/Country.cpp
- src/openvic-simulation/country/Country.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
Depends on: #48
Searches for countries.txt then loads the country from the directed file
Passes tests
> Add Country Loading

- src/openvic-simulation/Modifier.cpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/politics/NationalValue.cpp
- src/openvic-simulation/politics/NationalValue.hpp
- src/openvic-simulation/politics/PoliticsManager.hpp
Loads national values, tests passing.
Also adds 3 modifier effects related to mobilisation used by vanilla NVs.
> Implement National Values Loading

- src/openvic-simulation/types/IdentifierRegistry.hpp
Change `has_identifier` to use `map::contains`
Change `has_index` to compare using size
Change `get_item_identifiers` to use vector ctor over reserve
Change `expect_item_decimal_map` to use move for fixed_point_t
Add shortcut to to `add_item` when calling `duplicate_ignore_callback`
> Add some low priority optimizations in IdentifierRegistry

- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/misc/Define.cpp
- src/openvic-simulation/misc/Define.hpp
- src/openvic-simulation/types/IdentifierRegistry.hpp
Caches start_date and end_date in DefineManager
Add static `get_property` and HASID_PROPERTY macro to HasIdentifier
> Add Defines Loading

- src/openvic-simulation/country/Country.cpp
- src/openvic-simulation/country/Country.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/dataloader/NodeTools.cpp
- src/openvic-simulation/dataloader/NodeTools.hpp
- src/openvic-simulation/history/CountryHistory.cpp
- src/openvic-simulation/history/CountryHistory.hpp
- src/openvic-simulation/history/HistoryManager.hpp
- src/openvic-simulation/military/Deployment.cpp
- src/openvic-simulation/military/Deployment.hpp
- src/openvic-simulation/military/LeaderTrait.cpp
- src/openvic-simulation/military/LeaderTrait.hpp
- src/openvic-simulation/military/MilitaryManager.hpp
- src/openvic-simulation/military/Unit.hpp
- src/openvic-simulation/types/Date.cpp
- src/openvic-simulation/types/Date.hpp
Loads country histories and Order of Battle files, tests passing.
> Country History & Order of Battle Loading

- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/history/CountryHistory.cpp
- src/openvic-simulation/history/CountryHistory.hpp
- src/openvic-simulation/history/HistoryManager.hpp
- src/openvic-simulation/history/ProvinceHistory.cpp
- src/openvic-simulation/history/ProvinceHistory.hpp
Loads province history, tests passing.
> Implement Province History Loading

- src/openvic-simulation/country/Country.hpp
- src/openvic-simulation/economy/Building.cpp
- src/openvic-simulation/economy/Building.hpp
- src/openvic-simulation/history/DiplomaticHistory.hpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
- Adds a function to apply province history to provinces
- Adds missing properties to Province structure
- Adds setter to `BuildingInstance` level
Tests passing.
> Apply Province Histories

- src/openvic-simulation/country/Country.hpp
- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/utility/Getters.hpp
Adds simple `PROPERTY_RW` macro for getters & setters.
Adds `CountryInstance` class to represent in-game countries.
Adds function to apply country history to country instances.
> Country History Improvements

- .vscode/launch.json
- src/openvic-simulation/Modifier.cpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/politics/NationalFocus.cpp
- src/openvic-simulation/politics/NationalFocus.hpp
- src/openvic-simulation/politics/PoliticsManager.hpp
Loads `common/national_focus.txt`
Adds launch.json for MSVC debugging
Fixes bug in `expect_modifier_value_and_keys_and_default()`
Needs testing.
> Implement National Focus Loading

- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/misc/Event.cpp
- src/openvic-simulation/misc/Event.hpp
NodeTools based event loader. Completion depends on scripting support.
> Skeleton Event Loading

- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/misc/Decision.cpp
- src/openvic-simulation/misc/Decision.hpp
Well, did as much of decision loading as we can do right now. Which means not very much. Still missing:
- `potential` (condition for the decision to show)
- `allow` (condition for the decision to be available to take)
- `effect` (effect of the decision)
- `ai_will_do` (AI chance of taking it)
> Decision dataloading (kind of)

- src/openvic-simulation/map/Map.cpp
- src/openvic-simulation/map/Province.hpp
Calculate the province center and store it in positions.
Center  = sum x / pixel count , sum y / pixel count
> Calculate province center

- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/history/Bookmark.cpp
- src/openvic-simulation/history/Bookmark.hpp
- src/openvic-simulation/history/CountryHistory.cpp
- src/openvic-simulation/history/CountryHistory.hpp
- src/openvic-simulation/history/HistoryMap.cpp
- src/openvic-simulation/history/HistoryMap.hpp
- src/openvic-simulation/history/ProvinceHistory.cpp
- src/openvic-simulation/history/ProvinceHistory.hpp
- src/openvic-simulation/interface/UI.hpp
- src/openvic-simulation/map/Map.cpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
- src/openvic-simulation/misc/Decision.cpp
- src/openvic-simulation/politics/Government.cpp
- src/openvic-simulation/politics/Government.hpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
This one was annoying. The code itself should work fine (I tested it), but I don't rule out typos or small mistakes - it is pretty late, after all.
Also, I had to change the access level of a few things to make a sensible loading flow. I expect there to be better ways I didn't think of to go about this.
> Pop History Loading (with the new system)

- src/openvic-simulation/map/Map.cpp
- src/openvic-simulation/map/Province.cpp
- src/openvic-simulation/map/Province.hpp
Calculate distances for adjacencies using unit position with fallback to province center.
> Calculate distance between adjacencies

- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/misc/Event.cpp
- src/openvic-simulation/misc/Event.hpp
This one was pretty straightforward. The one thing I'm not sure on is that conversion from string to int - is there a better way?
> on_action dataloading

- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/misc/Modifier.cpp
- src/openvic-simulation/politics/Issue.cpp
- src/openvic-simulation/politics/Issue.hpp
- src/openvic-simulation/politics/PoliticsManager.hpp
Tested, seems to work fine. There can plausibly be some typos, but the change is relatively small so another pair of eyes can check that quite rapidly.
> Dataloading Issue/Reform Modifiers and RuleSets

- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
Cleaned up an old branch Farmington did some work on so we can get it merged.
> Added pop properties (size changes, literacy)

- src/openvic-simulation/types/IdentifierRegistry.hpp
Also changed `IdentifierRegistry.hpp` to use `NodeTools` function concepts instead of `std::function` based types, since everything is defined in the header already anyway.
> Added expect_item_dictionary_and_default

- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/diplomacy/CountryRelation.cpp
- src/openvic-simulation/diplomacy/CountryRelation.hpp
- src/openvic-simulation/diplomacy/DiplomacyManager.hpp
- src/openvic-simulation/diplomacy/DiplomaticAction.cpp
- src/openvic-simulation/diplomacy/DiplomaticAction.hpp
- src/openvic-simulation/utility/ErrorMacros.hpp
- src/openvic-simulation/utility/StringUtils.hpp
- src/openvic-simulation/utility/Utility.hpp
Change `DiplomaticAction::Argument` to refer to `CountryInstance*` instead of `Country*`
Add `GameManager&` argument to `DiplomaticActionManager::setup_diplomatic_actions`
Add some ErrorMacros, likely and unlikely macros and stringization macros (based on Godot's macros)
Implement `increase_relations` DiplomaticAction commit function
Implement `decrease_relations` DiplomaticAction commit function
> Add skeleton CountryRelationManager

- .github/workflows/builds.yml
Update openvic-dataloader to OpenVicProject/OpenVic-Dataloader@9f06c13977efce7d0dd0a849a1b3611ebdab6451
Update lexy-vdf to OpenVicProject/lexy-vdf@dbe24a241645eb9cc22de96136c1f0a2d6019aff
> Update build workflow actions

- src/openvic-simulation/country/Country.cpp
- src/openvic-simulation/country/Country.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
Country unit colours added to Country struct and loaded in from the country_colours.txt file
> Implemented loading of country unit colours

- src/openvic-simulation/country/Country.cpp
- src/openvic-simulation/country/Country.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/military/Deployment.cpp
- src/openvic-simulation/military/Deployment.hpp
- src/openvic-simulation/military/Leader.cpp
- src/openvic-simulation/military/Leader.hpp
- src/openvic-simulation/military/MilitaryManager.hpp
- src/openvic-simulation/military/UnitInstance.cpp
- src/openvic-simulation/military/UnitInstance.hpp
- src/openvic-simulation/military/UnitType.cpp
- src/openvic-simulation/military/UnitType.hpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
- src/openvic-simulation/research/Invention.cpp
- src/openvic-simulation/research/Invention.hpp
- src/openvic-simulation/research/Technology.cpp
- src/openvic-simulation/research/Technology.hpp
defining the various instance types
> Military unit instance

- .gitmodules
- deps/SCsub
Resolves #141
See https://github.com/mattreecebentley/plf_colony and https://plflib.org/colony.htm
> Add mattreecebentley/plf_colony

- src/headless/main.cpp
- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
- src/openvic-simulation/dataloader/NodeTools.hpp
- src/openvic-simulation/history/CountryHistory.cpp
- src/openvic-simulation/history/CountryHistory.hpp
- src/openvic-simulation/history/ProvinceHistory.cpp
- src/openvic-simulation/history/ProvinceHistory.hpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/map/Mapmode.cpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/map/ProvinceInstance.hpp
- src/openvic-simulation/map/State.cpp
- src/openvic-simulation/map/State.hpp
- src/openvic-simulation/military/UnitInstanceGroup.cpp
- src/openvic-simulation/military/UnitInstanceGroup.hpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/types/HasIdentifier.hpp
- src/openvic-simulation/types/IdentifierRegistry.hpp
- src/openvic-simulation/types/IndexedMap.hpp
Some parts are still WIP/subject to change, particularly country instance variables and gamestate updating.
> Fleshing out Country, State and Province instances + history

- src/openvic-simulation/economy/BuildingType.cpp
- src/openvic-simulation/map/Crime.cpp
- src/openvic-simulation/map/Crime.hpp
- src/openvic-simulation/map/MapDefinition.cpp
- src/openvic-simulation/map/Region.cpp
- src/openvic-simulation/map/Region.hpp
- src/openvic-simulation/map/TerrainType.cpp
- src/openvic-simulation/military/LeaderTrait.cpp
- src/openvic-simulation/modifier/Modifier.cpp
- src/openvic-simulation/modifier/Modifier.hpp
- src/openvic-simulation/politics/Issue.cpp
- src/openvic-simulation/politics/Issue.hpp
- src/openvic-simulation/politics/NationalFocus.cpp
- src/openvic-simulation/politics/NationalValue.cpp
- src/openvic-simulation/research/Invention.cpp
- src/openvic-simulation/research/Technology.cpp
These will be useful for organising modifiers in tooltips, e.g. collecting together tech into a single "From tech" line
> Modifier types

- src/openvic-simulation/economy/BuildingType.cpp
- src/openvic-simulation/economy/GoodDefinition.cpp
- src/openvic-simulation/map/Crime.cpp
- src/openvic-simulation/map/Crime.hpp
- src/openvic-simulation/map/MapDefinition.cpp
- src/openvic-simulation/map/Region.cpp
- src/openvic-simulation/map/Region.hpp
- src/openvic-simulation/map/TerrainType.cpp
- src/openvic-simulation/military/LeaderTrait.cpp
- src/openvic-simulation/military/UnitType.cpp
- src/openvic-simulation/modifier/Modifier.cpp
- src/openvic-simulation/modifier/Modifier.hpp
- src/openvic-simulation/politics/Issue.cpp
- src/openvic-simulation/politics/Issue.hpp
- src/openvic-simulation/politics/NationalFocus.cpp
- src/openvic-simulation/politics/NationalFocus.hpp
- src/openvic-simulation/politics/NationalValue.cpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/research/Invention.cpp
- src/openvic-simulation/research/Technology.cpp
- Fix unit modifier localisation keys
- Move national focus specific effects to custom variables rather than general modifier effects (this gets around issues with their localisation too)
> Fix modifiers

- src/openvic-simulation/modifier/ModifierEffect.hpp
- src/openvic-simulation/modifier/ModifierEffectCache.cpp
- src/openvic-simulation/modifier/ModifierEffectCache.hpp
- src/openvic-simulation/modifier/ModifierManager.cpp
- src/openvic-simulation/modifier/ModifierManager.hpp
https://discord.com/channels/1063392556160909312/1077648343863406613/1300768130666205256
> movement_cost is a province modifier

- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
> Remove unused (and inaccurate) fixed point members

- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/map/ProvinceInstance.hpp
Cleans up the code a lot at the cost of storing a reference to a singleton per province.
> ModifierEffectCache & location to fields

- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/InstanceManager.hpp
- src/openvic-simulation/economy/GoodInstance.cpp
- src/openvic-simulation/economy/GoodInstance.hpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
- src/openvic-simulation/economy/trading/MarketInstance.cpp
- src/openvic-simulation/economy/trading/MarketInstance.hpp
- src/openvic-simulation/economy/trading/MarketSellOrder.cpp
- src/openvic-simulation/economy/trading/MarketSellOrder.hpp
- src/openvic-simulation/economy/trading/SellResult.hpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/map/ProvinceInstance.hpp
Since producers have no stockpile, they will try to sell all their produce every day.
They take whatever price is offered. The market will later handle price and price change restrictions.
For now it just uses the base price.
> Add market placeholder

- .github/workflows/dependabot.yml
Adds a dependabot profile so that changes to scripts and dataloader open propagation PRs automatically.
> Create dependabot.yml for Sim Repo

- src/openvic-simulation/dataloader/NodeTools.cpp
- src/openvic-simulation/dataloader/NodeTools.hpp
- src/openvic-simulation/interface/GFXObject.cpp
- src/openvic-simulation/interface/GFXObject.hpp
- src/openvic-simulation/interface/GUI.cpp
- src/openvic-simulation/interface/GUI.hpp
- src/openvic-simulation/map/ProvinceDefinition.cpp
- src/openvic-simulation/map/ProvinceDefinition.hpp
- src/openvic-simulation/types/TextFormat.hpp
Very very in progress define loading for gfx objects.
- Lots of verifying to do (int64 vs fixed_point_t, are things correctly marked case sensitive vs insensitive, are properties EXACTLY_ONE or ZERO_OR_ONE, etc.)
- Need to reorganize/improve some datatypes (extraction of format_t to a datatype, improve unlabelled vec3 and vec4 types).
> Load Gfxobjects

- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/InstanceManager.hpp
- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/map/ProvinceInstance.hpp
- src/openvic-simulation/types/FlagStrings.cpp
- src/openvic-simulation/types/FlagStrings.hpp
Adds two files called Flags.hpp and Flags.cpp, and use them for country, province and global flags
> Add flag struct

- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/map/ProvinceInstance.hpp
- src/openvic-simulation/map/State.cpp
- src/openvic-simulation/map/State.hpp
- src/openvic-simulation/politics/PoliticsInstanceManager.cpp
- src/openvic-simulation/politics/PoliticsInstanceManager.hpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
- src/openvic-simulation/types/IndexedMap.hpp
- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
- src/openvic-simulation/types/fixed_point/FixedPointMap.hpp
Also fixes a bug with starting ideology unlocks
> Calculate more data needed for conditions

- src/openvic-simulation/GameManager.cpp
- src/openvic-simulation/GameManager.hpp
- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/InstanceManager.hpp
- src/openvic-simulation/dataloader/Dataloader.cpp
- src/openvic-simulation/dataloader/Dataloader.hpp
- src/openvic-simulation/economy/EconomyManager.hpp
- src/openvic-simulation/economy/production/ProductionType.cpp
- src/openvic-simulation/economy/production/ProductionType.hpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
- src/openvic-simulation/misc/GameRulesManager.hpp
Context: https://discord.com/channels/1063392556160909312/1064542494114725909/1331560403112693793
Weird Paradox behaviour
> Accurately mimic Victoria 2's farm & mine mechanics + game rules

- src/openvic-simulation/economy/GoodInstance.cpp
- src/openvic-simulation/economy/GoodInstance.hpp
- src/openvic-simulation/economy/production/ArtisanalProducer.cpp
- src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.hpp
- src/openvic-simulation/economy/production/FactoryProducer.cpp
- src/openvic-simulation/economy/trading/BuyUpToOrder.hpp
- src/openvic-simulation/interface/GFXObject.hpp
- src/openvic-simulation/map/MapDefinition.cpp
- src/openvic-simulation/misc/GameRulesManager.hpp
- src/openvic-simulation/pop/Pop.hpp
Implementation of the python code. See also https://discord.com/channels/1063392556160909312/1105422811809452072/1301900686904000527
> Dynamic pricing

- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
- src/openvic-simulation/economy/GoodDefinition.cpp
- src/openvic-simulation/economy/production/ArtisanalProducer.cpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
- src/openvic-simulation/economy/trading/MarketInstance.cpp
- src/openvic-simulation/economy/trading/MarketInstance.hpp
- src/openvic-simulation/interface/GFXObject.cpp
- src/openvic-simulation/map/ProvinceInstance.hpp
- src/openvic-simulation/politics/Rule.cpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
- src/openvic-simulation/utility/StringUtils.hpp
Gold mines refers to any production type that outputs a good with `money = yes`. These are directly converted to cash and not traded.
Also both artisans & rgo now report their daily production to the province controller (if any).
The country can sum the total production and derive the gold income (in budget) from this.
> Support gold mines & report production

- src/openvic-simulation/types/IdentifierRegistry.hpp
- src/openvic-simulation/types/OrderedContainers.hpp
- src/openvic-simulation/utility/Deque.hpp
This addresses https://github.com/microsoft/STL/issues/147#issuecomment-1090148740
> Replace MSVC STL deque to support 512 block size

- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
- src/openvic-simulation/economy/GoodInstance.cpp
- src/openvic-simulation/economy/GoodInstance.hpp
- src/openvic-simulation/economy/production/ArtisanalProducer.cpp
- src/openvic-simulation/economy/production/ArtisanalProducer.hpp
- src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.cpp
- src/openvic-simulation/economy/production/ArtisanalProducerFactoryPattern.hpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
- src/openvic-simulation/economy/production/ResourceGatheringOperation.hpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/map/ProvinceInstance.hpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
- src/openvic-simulation/pop/PopValuesFromProvince.cpp
- src/openvic-simulation/pop/PopValuesFromProvince.hpp
> Pop needs & spending

- src/openvic-simulation/InstanceManager.cpp
- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
- src/openvic-simulation/economy/production/ArtisanalProducer.cpp
- src/openvic-simulation/misc/GameRulesManager.hpp
- src/openvic-simulation/pop/Pop.cpp
Will break UI due to name changes and removal of a property.
I'll fix that in a follow up PR.
> Record country demand

- src/openvic-simulation/economy/GoodInstance.hpp
- src/openvic-simulation/economy/trading/GoodMarket.hpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
Resolves comments for https://github.com/OpenVicProject/OpenVic-Simulation/pull/316
I clicked resolve before pushing changes....
> Resolved comments on fix_need_modifiers PR

- src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
- src/openvic-simulation/pop/Pop.cpp
In the current placeholder HRM all available workers are hired on a day to day basis.
This means we have to clear employees daily.
> Fix RGO hiring

- src/openvic-simulation/economy/trading/GoodMarket.cpp
- src/openvic-simulation/economy/trading/MarketInstance.cpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/utility/CompilerFeatureTesting.hpp
Fix try_parallel_for_each treating mac as using GCC library
> Add parallel_for_each range

- src/openvic-simulation/types/fixed_point/Atomic.hpp
- src/openvic-simulation/utility/Utility.hpp
> Add std::atomic<fixed_point_t> specialization

- src/openvic-simulation/economy/production/ArtisanalProducer.cpp
- src/openvic-simulation/pop/Pop.cpp
- src/openvic-simulation/pop/Pop.hpp
Use atomic_fixed_point_t for += and -= opertions.
Use .at(key) instead of indexing to avoid try_emplace.
> Thread safe pop tick and callbacks

- src/openvic-simulation/economy/production/ArtisanalProducer.hpp
> Improve thread safety comment for artisan

- src/openvic-simulation/diplomacy/CountryRelation.cpp
- src/openvic-simulation/diplomacy/CountryRelation.hpp
- src/openvic-simulation/diplomacy/DiplomaticAction.cpp
- src/openvic-simulation/diplomacy/DiplomaticAction.hpp
Add country relation functions
Add country alliance functions
Add countries at war functions
Add country military access functions
Add country command units functions
Add country vision functions
Add country opinion functions
Add country influence functions
Add country discredit functions
Add country embassy ban functions
Add end_alliance action
Add give_military_access action
Add end_war_subsidies action
Add ban_embassy action
Add remove_from_foreign_sphere action
Add remove_from_own_sphere action
Add influence_cost to DiplomaticActionType
> Implement country diplomatic relation support

- src/openvic-simulation/types/IndexedMap.hpp
- src/openvic-simulation/utility/BMP.hpp
Needed for [OpenVic#395](https://github.com/OpenVicProject/OpenVic/pull/395)
> Minor BMP and IndexedMap cleanup

- src/openvic-simulation/economy/trading/GoodMarket.cpp
- src/openvic-simulation/economy/trading/GoodMarket.hpp
- src/openvic-simulation/economy/trading/MarketInstance.cpp
- src/openvic-simulation/economy/trading/MarketInstance.hpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/map/ProvinceInstance.cpp
- src/openvic-simulation/utility/ParallelProcessorWithSharesValues.hpp
Similar to how provinces reuse PopValuesFromProvince, GoodMarket can reuse 2 vectors.
> Reuse GoodMarket vectors

- src/openvic-simulation/dataloader/NodeTools.cpp
- src/openvic-simulation/map/MapDefinition.cpp
- src/openvic-simulation/misc/Event.cpp
- src/openvic-simulation/testing/TestScript.cpp
- src/openvic-simulation/testing/TestScript.hpp
- src/openvic-simulation/testing/Testing.cpp
- src/openvic-simulation/testing/Testing.hpp
- src/openvic-simulation/types/Colour.hpp
- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
- src/openvic-simulation/utility/StringUtils.hpp
Fix string_to_uint64 and string_to_int64 to act like std::from_chars
Add constexpr StringUtils::from_chars
> Fix occurrences of undefined behavior

- .gitmodules
- deps/SCsub
- src/openvic-simulation/InstanceManager.hpp
- src/openvic-simulation/console/ConsoleInstance.hpp
- src/openvic-simulation/dataloader/NodeTools.cpp
- src/openvic-simulation/dataloader/NodeTools.hpp
- src/openvic-simulation/economy/production/ProductionType.cpp
- src/openvic-simulation/interface/GUI.cpp
- src/openvic-simulation/interface/LoadBase.hpp
- src/openvic-simulation/map/MapDefinition.cpp
- src/openvic-simulation/map/Mapmode.hpp
- src/openvic-simulation/misc/SimulationClock.hpp
- src/openvic-simulation/modifier/ModifierManager.cpp
- src/openvic-simulation/modifier/ModifierManager.hpp
- src/openvic-simulation/politics/NationalFocus.cpp
- src/openvic-simulation/politics/Rule.cpp
- src/openvic-simulation/scripts/Condition.cpp
- src/openvic-simulation/utility/Logger.hpp
Add Spartan322/std_function@dbf2df963e6d0a47ab5e21e93c838233cd8b6b03
Move std::function usage to function2 functors
> Add Naios/function2@43fc0ca473ecb081918709bd7d524d84c2ff8dce

- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
- tests/src/types/FixedPoint.cpp
Add `fixed_point_t::from_chars_with_plus` method
Add positive fixed_point_t parse assertion
Add negative fixed_point_t parse assertion
> Add `fixed_point_t::from_chars` method

- tests/src/Helper.hpp
- tests/src/dataloader/NodeTools.cpp
- Depends on #370
- Depends on #371
- Depends on #372 
- Depends on #374 
- Depends on #375 
- Depends on #377 
Add CHECK_RETURN_BOOL test macro
Add CHECK_FALSE_RETURN_BOOL test macro
> Add NodeTools unit tests

- src/openvic-simulation/economy/BuildingInstance.cpp
- src/openvic-simulation/economy/BuildingInstance.hpp
- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
Fix fixed_point_t binary operators
Add `fixed_point_t::to<T>` conversion function
> Change `BuildingInstance::expansion_progress` to fixed_point_t

- src/openvic-simulation/types/fixed_point/FixedPoint.cpp
- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
- tests/src/types/FixedPoint.cpp
Add fmt formatter support to fixed_point_t
Optimize `operator<<(std::ostream&, fixed_point_t const&)`
Add unit tests for fixed_point_t string methods
> Add stack string method to fixed_point_t

- .github/workflows/builds.yml
- .github/workflows/cache_cleanup.yml
Simplify concurrency group in builds workflow
Remove forced check in builds workflow
Add emoji to builds workflow name
Add cache_cleanup on PR close
> Add merge_group support to builds workflow

- src/headless/main.cpp
- src/openvic-simulation/map/MapDefinition.cpp
- src/openvic-simulation/map/MapDefinition.hpp
- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/pathfinding/AStarPathing.hpp
- src/openvic-simulation/pathfinding/FringePathing.hpp
- src/openvic-simulation/pathfinding/PointMap.cpp
- src/openvic-simulation/pathfinding/PointMap.hpp
Add land and sea AStarPathing to MapInstance
Add `PointMap::try_add_point`
Add `PointMap::shrink_to_fit`
Fix PointMap proxy helper functions
Add pathfinding tests to headless simulation
> Add land and sea PointMap to MapDefinition

- .gitignore
- .gitmodules
- SConstruct
- tests/benchmarks/SCsub
- tests/benchmarks/deps/SCsub
- tests/benchmarks/src/dataloading/Dataloading.cpp
- tests/deps/SCsub
Add nanobench as benchmarks dependency
See https://github.com/Spartan322/nanobench/tree/disable/exceptions-and-rtti
> Add Dataloading benchmarks

- src/openvic-simulation/economy/production/ResourceGatheringOperation.cpp
Modifiers from technology are taken into account when determining province size.
> Include tech modifiers for rgo province size

- src/openvic-simulation/types/fixed_point/FixedPoint.hpp
- tests/src/types/FixedPoint.cpp
Add negative fraction parse and string tests
> Fix parsing fixed_point_t negative fractions as positive

- src/openvic-simulation/map/MapDefinition.cpp
Fix break/continue lacking braces in MapDefinition
> Fix space/tab indentation mixing in MapDefinition

- src/openvic-simulation/pathfinding/PathingBase.hpp
Add `PathingBase::generate_path_result`
Add early exit for disabled from point in PathingBase
> Add `PathingBase::get_iterator_by_id`

- src/openvic-simulation/types/Vector.hpp
- src/openvic-simulation/types/VectorN.inc
- src/openvic-simulation/utility/Deque.hpp
- src/openvic-simulation/utility/ForwardableSpan.hpp
> Standardize _detail namespace names

- src/openvic-simulation/types/CowPtr.hpp
- src/openvic-simulation/types/NullMutex.hpp
- src/openvic-simulation/types/Signal.hpp
- src/openvic-simulation/types/SpinMutex.hpp
- tests/src/types/Signal.cpp
Add cow_ptr for copy-on-write data
Add null_mutex
Add spin_mutex
Add signal tests
> Add signal and signal_property based on sigslot

- src/openvic-simulation/pathfinding/AStarPathing.hpp
- src/openvic-simulation/pathfinding/FringePathing.hpp
- src/openvic-simulation/pathfinding/PathingBase.hpp
- src/openvic-simulation/pathfinding/PointMap.cpp
- src/openvic-simulation/pathfinding/PointMap.hpp
> Add invalidation signals to pathfinding classes

- src/openvic-simulation/map/MapInstance.cpp
- src/openvic-simulation/map/MapInstance.hpp
- src/openvic-simulation/military/UnitInstanceGroup.hpp
- src/openvic-simulation/pathfinding/AStarPathing.cpp
- src/openvic-simulation/pathfinding/AStarPathing.hpp
Add exiled property to ArmyInstance
> Add ArmyAStarPathing for ArmyInstance pathing

- src/openvic-simulation/country/CountryInstance.cpp
Context: https://discord.com/channels/1063392556160909312/1105422859641290803/1389332807398068274
> Fix admin efficiency calculation

- src/openvic-simulation/country/CountryInstance.cpp
> Add this check for `CountryInstance::can_army_units_enter`

- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
Tariffs = tariff rate * import value * tariff efficiency
Tariff efficiency = min(1, administrative_efficiency_from_administrators + BASE_TARIFF_EFFICIENCY)
> Added get_tariff_efficiency to CountryInstance

- src/openvic-simulation/country/CountryInstance.cpp
- src/openvic-simulation/country/CountryInstance.hpp
The alternative is to iterate through every country instance and find the country with the sphere opinion.
> Add sphere_owner property to CountryInstance

- src/openvic-simulation/utility/reactive/MutableState.hpp
std::forward requires specifying the type...
> Specify type on forward
